# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.catalogs_api import CatalogsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCatalogsApi(unittest.TestCase):
    """CatalogsApi unit test stubs"""

    def setUp(self):
        self.api = CatalogsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_app_catalog(self):
        """Test case for delete_app_catalog

        Delete a catalog  # noqa: E501
        """
        pass

    def test_get_app_catalog(self):
        """Test case for get_app_catalog

        Get a catalog  # noqa: E501
        """
        pass

    def test_get_app_catalogs(self):
        """Test case for get_app_catalogs

        Get the list of owned catalogs  # noqa: E501
        """
        pass

    def test_patch_app_catalog(self):
        """Test case for patch_app_catalog

        Update a catalog  # noqa: E501
        """
        pass

    def test_post_app_catalog(self):
        """Test case for post_app_catalog

        Create a new catalog  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
