# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.apirestv1categories_labels import Apirestv1categoriesLabels  # noqa: E501
from swagger_client.rest import ApiException


class TestApirestv1categoriesLabels(unittest.TestCase):
    """Apirestv1categoriesLabels unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApirestv1categoriesLabels(self):
        """Test Apirestv1categoriesLabels"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.apirestv1categories_labels.Apirestv1categoriesLabels()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
