# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.apirestv1assets_link_self import Apirestv1assetsLinkSelf  # noqa: E501
from swagger_client.rest import ApiException


class TestApirestv1assetsLinkSelf(unittest.TestCase):
    """Apirestv1assetsLinkSelf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApirestv1assetsLinkSelf(self):
        """Test Apirestv1assetsLinkSelf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.apirestv1assets_link_self.Apirestv1assetsLinkSelf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
