# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.apirestv1categories_values_attribute_codeattribute_uuidchannel_codelocale_code import Apirestv1categoriesValuesAttributeCodeattributeUuidchannelCodelocaleCode  # noqa: E501
from swagger_client.rest import ApiException


class TestApirestv1categoriesValuesAttributeCodeattributeUuidchannelCodelocaleCode(unittest.TestCase):
    """Apirestv1categoriesValuesAttributeCodeattributeUuidchannelCodelocaleCode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApirestv1categoriesValuesAttributeCodeattributeUuidchannelCodelocaleCode(self):
        """Test Apirestv1categoriesValuesAttributeCodeattributeUuidchannelCodelocaleCode"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.apirestv1categories_values_attribute_codeattribute_uuidchannel_codelocale_code.Apirestv1categoriesValuesAttributeCodeattributeUuidchannelCodelocaleCode()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
