# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.product_uuid_list import ProductUuidList  # noqa: E501
from swagger_client.rest import ApiException


class TestProductUuidList(unittest.TestCase):
    """ProductUuidList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProductUuidList(self):
        """Test ProductUuidList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.product_uuid_list.ProductUuidList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
