# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.association_type_api import AssociationTypeApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAssociationTypeApi(unittest.TestCase):
    """AssociationTypeApi unit test stubs"""

    def setUp(self):
        self.api = AssociationTypeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_association_types_get(self):
        """Test case for association_types_get

        Get an association type  # noqa: E501
        """
        pass

    def test_association_types_get_list(self):
        """Test case for association_types_get_list

        Get a list of association types  # noqa: E501
        """
        pass

    def test_association_types_patch(self):
        """Test case for association_types_patch

        Update/create an association type  # noqa: E501
        """
        pass

    def test_association_types_post(self):
        """Test case for association_types_post

        Create a new association type  # noqa: E501
        """
        pass

    def test_several_association_types_patch(self):
        """Test case for several_association_types_patch

        Update/create several association types  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
