# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.apirestv1assetfamiliesasset_family_codeassets_values_attribute_code import Apirestv1assetfamiliesassetFamilyCodeassetsValuesAttributeCode  # noqa: E501
from swagger_client.rest import ApiException


class TestApirestv1assetfamiliesassetFamilyCodeassetsValuesAttributeCode(unittest.TestCase):
    """Apirestv1assetfamiliesassetFamilyCodeassetsValuesAttributeCode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApirestv1assetfamiliesassetFamilyCodeassetsValuesAttributeCode(self):
        """Test Apirestv1assetfamiliesassetFamilyCodeassetsValuesAttributeCode"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.apirestv1assetfamiliesasset_family_codeassets_values_attribute_code.Apirestv1assetfamiliesassetFamilyCodeassetsValuesAttributeCode()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
