# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.reference_entity_api import ReferenceEntityApi  # noqa: E501
from swagger_client.rest import ApiException


class TestReferenceEntityApi(unittest.TestCase):
    """ReferenceEntityApi unit test stubs"""

    def setUp(self):
        self.api = ReferenceEntityApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_reference_entities(self):
        """Test case for get_reference_entities

        Get list of reference entities  # noqa: E501
        """
        pass

    def test_get_reference_entities_code(self):
        """Test case for get_reference_entities_code

        Get a reference entity  # noqa: E501
        """
        pass

    def test_patch_reference_entity_code(self):
        """Test case for patch_reference_entity_code

        Update/create a reference entity  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
