# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.apirestv1attributegroups_labels import Apirestv1attributegroupsLabels  # noqa: E501
from swagger_client.rest import ApiException


class TestApirestv1attributegroupsLabels(unittest.TestCase):
    """Apirestv1attributegroupsLabels unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApirestv1attributegroupsLabels(self):
        """Test Apirestv1attributegroupsLabels"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.apirestv1attributegroups_labels.Apirestv1attributegroupsLabels()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
