# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.product_model_api import ProductModelApi  # noqa: E501
from swagger_client.rest import ApiException


class TestProductModelApi(unittest.TestCase):
    """ProductModelApi unit test stubs"""

    def setUp(self):
        self.api = ProductModelApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_product_models_code(self):
        """Test case for delete_product_models_code

        Delete a product model  # noqa: E501
        """
        pass

    def test_get_product_model_draft_code(self):
        """Test case for get_product_model_draft_code

        Get a draft  # noqa: E501
        """
        pass

    def test_get_product_models(self):
        """Test case for get_product_models

        Get list of product models  # noqa: E501
        """
        pass

    def test_get_product_models_code(self):
        """Test case for get_product_models_code

        Get a product model  # noqa: E501
        """
        pass

    def test_patch_product_models(self):
        """Test case for patch_product_models

        Update/create several product models  # noqa: E501
        """
        pass

    def test_patch_product_models_code(self):
        """Test case for patch_product_models_code

        Update/create a product model  # noqa: E501
        """
        pass

    def test_post_product_model_proposal(self):
        """Test case for post_product_model_proposal

        Submit a draft for approval  # noqa: E501
        """
        pass

    def test_post_product_models(self):
        """Test case for post_product_models

        Create a new product model  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
