# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.measure_family_api import MeasureFamilyApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMeasureFamilyApi(unittest.TestCase):
    """MeasureFamilyApi unit test stubs"""

    def setUp(self):
        self.api = MeasureFamilyApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_measure_families_get(self):
        """Test case for measure_families_get

        Get a measure family  # noqa: E501
        """
        pass

    def test_measure_families_get_list(self):
        """Test case for measure_families_get_list

        Get list of measure familiy  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
