# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.product__uuid_api import ProductUuidApi  # noqa: E501
from swagger_client.rest import ApiException


class TestProductUuidApi(unittest.TestCase):
    """ProductUuidApi unit test stubs"""

    def setUp(self):
        self.api = ProductUuidApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_products_uuid_uuid(self):
        """Test case for delete_products_uuid_uuid

        Delete a product  # noqa: E501
        """
        pass

    def test_get_draft_uuid_uuid(self):
        """Test case for get_draft_uuid_uuid

        Get a draft  # noqa: E501
        """
        pass

    def test_get_products_uuid(self):
        """Test case for get_products_uuid

        Get list of products  # noqa: E501
        """
        pass

    def test_get_products_uuid_uuid(self):
        """Test case for get_products_uuid_uuid

        Get a product  # noqa: E501
        """
        pass

    def test_patch_products_uuid(self):
        """Test case for patch_products_uuid

        Update/create several products  # noqa: E501
        """
        pass

    def test_patch_products_uuid_uuid(self):
        """Test case for patch_products_uuid_uuid

        Update/create a product  # noqa: E501
        """
        pass

    def test_post_products_uuid(self):
        """Test case for post_products_uuid

        Create a new product  # noqa: E501
        """
        pass

    def test_post_proposal_uuid(self):
        """Test case for post_proposal_uuid

        Submit a draft for approval  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
