# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.attribute_api import AttributeApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAttributeApi(unittest.TestCase):
    """AttributeApi unit test stubs"""

    def setUp(self):
        self.api = AttributeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_attributes(self):
        """Test case for get_attributes

        Get list of attributes  # noqa: E501
        """
        pass

    def test_get_attributes_code(self):
        """Test case for get_attributes_code

        Get an attribute  # noqa: E501
        """
        pass

    def test_patch_attributes(self):
        """Test case for patch_attributes

        Update/create several attributes  # noqa: E501
        """
        pass

    def test_patch_attributes_code(self):
        """Test case for patch_attributes_code

        Update/create an attribute  # noqa: E501
        """
        pass

    def test_post_attributes(self):
        """Test case for post_attributes

        Create a new attribute  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
