# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.locale_api import LocaleApi  # noqa: E501
from swagger_client.rest import ApiException


class TestLocaleApi(unittest.TestCase):
    """LocaleApi unit test stubs"""

    def setUp(self):
        self.api = LocaleApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_locales(self):
        """Test case for get_locales

        Get a list of locales  # noqa: E501
        """
        pass

    def test_get_locales_code(self):
        """Test case for get_locales_code

        Get a locale  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
