# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.deprecated_asset import DeprecatedAsset  # noqa: E501
from swagger_client.rest import ApiException


class TestDeprecatedAsset(unittest.TestCase):
    """DeprecatedAsset unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeprecatedAsset(self):
        """Test DeprecatedAsset"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.deprecated_asset.DeprecatedAsset()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
