# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.reference_entities import ReferenceEntities  # noqa: E501
from swagger_client.rest import ApiException


class TestReferenceEntities(unittest.TestCase):
    """ReferenceEntities unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReferenceEntities(self):
        """Test ReferenceEntities"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.reference_entities.ReferenceEntities()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
