# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.apirestv1attributes_labels1 import Apirestv1attributesLabels1  # noqa: E501
from swagger_client.rest import ApiException


class TestApirestv1attributesLabels1(unittest.TestCase):
    """Apirestv1attributesLabels1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApirestv1attributesLabels1(self):
        """Test Apirestv1attributesLabels1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.apirestv1attributes_labels1.Apirestv1attributesLabels1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
