# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.asset_list import AssetList  # noqa: E501
from swagger_client.rest import ApiException


class TestAssetList(unittest.TestCase):
    """AssetList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAssetList(self):
        """Test AssetList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.asset_list.AssetList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
