# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.reference_entity_media_file_api import ReferenceEntityMediaFileApi  # noqa: E501
from swagger_client.rest import ApiException


class TestReferenceEntityMediaFileApi(unittest.TestCase):
    """ReferenceEntityMediaFileApi unit test stubs"""

    def setUp(self):
        self.api = ReferenceEntityMediaFileApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_reference_entity_media_files_code(self):
        """Test case for get_reference_entity_media_files_code

        Download the media file associated to a reference entity or a record  # noqa: E501
        """
        pass

    def test_post_reference_entity_media_files(self):
        """Test case for post_reference_entity_media_files

        Create a new media file for a reference entity or a record  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
