# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.apirestv1products_quantified_associations_quantified_association_type_code_product_models import Apirestv1productsQuantifiedAssociationsQuantifiedAssociationTypeCodeProductModels  # noqa: E501
from swagger_client.rest import ApiException


class TestApirestv1productsQuantifiedAssociationsQuantifiedAssociationTypeCodeProductModels(unittest.TestCase):
    """Apirestv1productsQuantifiedAssociationsQuantifiedAssociationTypeCodeProductModels unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApirestv1productsQuantifiedAssociationsQuantifiedAssociationTypeCodeProductModels(self):
        """Test Apirestv1productsQuantifiedAssociationsQuantifiedAssociationTypeCodeProductModels"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.apirestv1products_quantified_associations_quantified_association_type_code_product_models.Apirestv1productsQuantifiedAssociationsQuantifiedAssociationTypeCodeProductModels()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
