# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.product_uuid_examples import ProductUuidExamples  # noqa: E501
from swagger_client.rest import ApiException


class TestProductUuidExamples(unittest.TestCase):
    """ProductUuidExamples unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProductUuidExamples(self):
        """Test ProductUuidExamples"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.product_uuid_examples.ProductUuidExamples()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
