# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.apirestv1assetfamiliescode_product_selections import Apirestv1assetfamiliescodeProductSelections  # noqa: E501
from swagger_client.rest import ApiException


class TestApirestv1assetfamiliescodeProductSelections(unittest.TestCase):
    """Apirestv1assetfamiliescodeProductSelections unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApirestv1assetfamiliescodeProductSelections(self):
        """Test Apirestv1assetfamiliescodeProductSelections"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.apirestv1assetfamiliescode_product_selections.Apirestv1assetfamiliescodeProductSelections()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
