# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.apirestv1familiesfamily_codevariants_variant_attribute_sets import Apirestv1familiesfamilyCodevariantsVariantAttributeSets  # noqa: E501
from swagger_client.rest import ApiException


class TestApirestv1familiesfamilyCodevariantsVariantAttributeSets(unittest.TestCase):
    """Apirestv1familiesfamilyCodevariantsVariantAttributeSets unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApirestv1familiesfamilyCodevariantsVariantAttributeSets(self):
        """Test Apirestv1familiesfamilyCodevariantsVariantAttributeSets"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.apirestv1familiesfamily_codevariants_variant_attribute_sets.Apirestv1familiesfamilyCodevariantsVariantAttributeSets()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
