# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.pam_asset_api import PAMAssetApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPAMAssetApi(unittest.TestCase):
    """PAMAssetApi unit test stubs"""

    def setUp(self):
        self.api = PAMAssetApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_pam_assets(self):
        """Test case for get_pam_assets

        Get list of PAM assets  # noqa: E501
        """
        pass

    def test_get_pam_assets_code(self):
        """Test case for get_pam_assets_code

        Get a PAM asset  # noqa: E501
        """
        pass

    def test_patch_pam_assets(self):
        """Test case for patch_pam_assets

        Update/create several PAM assets  # noqa: E501
        """
        pass

    def test_patch_pam_assets_code(self):
        """Test case for patch_pam_assets_code

        Update/create a PAM asset  # noqa: E501
        """
        pass

    def test_post_pam_assets(self):
        """Test case for post_pam_assets

        Create a new PAM asset  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
