# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.apirestv1measurementfamilies_units_unit_code import Apirestv1measurementfamiliesUnitsUnitCode  # noqa: E501
from swagger_client.rest import ApiException


class TestApirestv1measurementfamiliesUnitsUnitCode(unittest.TestCase):
    """Apirestv1measurementfamiliesUnitsUnitCode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApirestv1measurementfamiliesUnitsUnitCode(self):
        """Test Apirestv1measurementfamiliesUnitsUnitCode"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.apirestv1measurementfamilies_units_unit_code.Apirestv1measurementfamiliesUnitsUnitCode()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
