# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.locale_list import LocaleList  # noqa: E501
from swagger_client.rest import ApiException


class TestLocaleList(unittest.TestCase):
    """LocaleList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLocaleList(self):
        """Test LocaleList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.locale_list.LocaleList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
