# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.reference_entity_record_api import ReferenceEntityRecordApi  # noqa: E501
from swagger_client.rest import ApiException


class TestReferenceEntityRecordApi(unittest.TestCase):
    """ReferenceEntityRecordApi unit test stubs"""

    def setUp(self):
        self.api = ReferenceEntityRecordApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_reference_entity_records(self):
        """Test case for get_reference_entity_records

        Get the list of the records of a reference entity  # noqa: E501
        """
        pass

    def test_get_reference_entity_records_code(self):
        """Test case for get_reference_entity_records_code

        Get a record of a given reference entity  # noqa: E501
        """
        pass

    def test_patch_reference_entity_records(self):
        """Test case for patch_reference_entity_records

        Update/create several reference entity records  # noqa: E501
        """
        pass

    def test_patch_reference_entity_records_code(self):
        """Test case for patch_reference_entity_records_code

        Update/create a record of a given reference entity  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
