# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.family_variant_api import FamilyVariantApi  # noqa: E501
from swagger_client.rest import ApiException


class TestFamilyVariantApi(unittest.TestCase):
    """FamilyVariantApi unit test stubs"""

    def setUp(self):
        self.api = FamilyVariantApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_families_family_code_variants(self):
        """Test case for get_families_family_code_variants

        Get list of family variants  # noqa: E501
        """
        pass

    def test_get_families_family_code_variants_code(self):
        """Test case for get_families_family_code_variants_code

        Get a family variant  # noqa: E501
        """
        pass

    def test_patch_families_family_code_variants(self):
        """Test case for patch_families_family_code_variants

        Update/create several family variants  # noqa: E501
        """
        pass

    def test_patch_families_family_code_variants_code(self):
        """Test case for patch_families_family_code_variants_code

        Update/create a family variant  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
