# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Apirestv1assetfamiliescodeTransformations(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'label': 'str',
        'filename_suffix': 'str',
        'filename_prefix': 'str',
        'source': 'Apirestv1assetfamiliescodeSource',
        'target': 'Apirestv1assetfamiliescodeTarget',
        'operations': 'Apirestv1assetfamiliescodeOperations'
    }

    attribute_map = {
        'label': 'label',
        'filename_suffix': 'filename_suffix',
        'filename_prefix': 'filename_prefix',
        'source': 'source',
        'target': 'target',
        'operations': 'operations'
    }

    def __init__(self, label=None, filename_suffix=None, filename_prefix=None, source=None, target=None, operations=None):  # noqa: E501
        """Apirestv1assetfamiliescodeTransformations - a model defined in Swagger"""  # noqa: E501
        self._label = None
        self._filename_suffix = None
        self._filename_prefix = None
        self._source = None
        self._target = None
        self._operations = None
        self.discriminator = None
        self.label = label
        if filename_suffix is not None:
            self.filename_suffix = filename_suffix
        if filename_prefix is not None:
            self.filename_prefix = filename_prefix
        self.source = source
        self.target = target
        self.operations = operations

    @property
    def label(self):
        """Gets the label of this Apirestv1assetfamiliescodeTransformations.  # noqa: E501

        The name of the transformation  # noqa: E501

        :return: The label of this Apirestv1assetfamiliescodeTransformations.  # noqa: E501
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label):
        """Sets the label of this Apirestv1assetfamiliescodeTransformations.

        The name of the transformation  # noqa: E501

        :param label: The label of this Apirestv1assetfamiliescodeTransformations.  # noqa: E501
        :type: str
        """
        if label is None:
            raise ValueError("Invalid value for `label`, must not be `None`")  # noqa: E501

        self._label = label

    @property
    def filename_suffix(self):
        """Gets the filename_suffix of this Apirestv1assetfamiliescodeTransformations.  # noqa: E501

        The suffix that will be appended to the source filename to generate the target filename. More details <a href='/concepts/asset-manager.html#target-filename'>here</a>.  # noqa: E501

        :return: The filename_suffix of this Apirestv1assetfamiliescodeTransformations.  # noqa: E501
        :rtype: str
        """
        return self._filename_suffix

    @filename_suffix.setter
    def filename_suffix(self, filename_suffix):
        """Sets the filename_suffix of this Apirestv1assetfamiliescodeTransformations.

        The suffix that will be appended to the source filename to generate the target filename. More details <a href='/concepts/asset-manager.html#target-filename'>here</a>.  # noqa: E501

        :param filename_suffix: The filename_suffix of this Apirestv1assetfamiliescodeTransformations.  # noqa: E501
        :type: str
        """

        self._filename_suffix = filename_suffix

    @property
    def filename_prefix(self):
        """Gets the filename_prefix of this Apirestv1assetfamiliescodeTransformations.  # noqa: E501

        The prefix that will be prepended to the source filename to generate the target filename. More details <a href='/concepts/asset-manager.html#target-filename'>here</a>.  # noqa: E501

        :return: The filename_prefix of this Apirestv1assetfamiliescodeTransformations.  # noqa: E501
        :rtype: str
        """
        return self._filename_prefix

    @filename_prefix.setter
    def filename_prefix(self, filename_prefix):
        """Sets the filename_prefix of this Apirestv1assetfamiliescodeTransformations.

        The prefix that will be prepended to the source filename to generate the target filename. More details <a href='/concepts/asset-manager.html#target-filename'>here</a>.  # noqa: E501

        :param filename_prefix: The filename_prefix of this Apirestv1assetfamiliescodeTransformations.  # noqa: E501
        :type: str
        """

        self._filename_prefix = filename_prefix

    @property
    def source(self):
        """Gets the source of this Apirestv1assetfamiliescodeTransformations.  # noqa: E501


        :return: The source of this Apirestv1assetfamiliescodeTransformations.  # noqa: E501
        :rtype: Apirestv1assetfamiliescodeSource
        """
        return self._source

    @source.setter
    def source(self, source):
        """Sets the source of this Apirestv1assetfamiliescodeTransformations.


        :param source: The source of this Apirestv1assetfamiliescodeTransformations.  # noqa: E501
        :type: Apirestv1assetfamiliescodeSource
        """
        if source is None:
            raise ValueError("Invalid value for `source`, must not be `None`")  # noqa: E501

        self._source = source

    @property
    def target(self):
        """Gets the target of this Apirestv1assetfamiliescodeTransformations.  # noqa: E501


        :return: The target of this Apirestv1assetfamiliescodeTransformations.  # noqa: E501
        :rtype: Apirestv1assetfamiliescodeTarget
        """
        return self._target

    @target.setter
    def target(self, target):
        """Sets the target of this Apirestv1assetfamiliescodeTransformations.


        :param target: The target of this Apirestv1assetfamiliescodeTransformations.  # noqa: E501
        :type: Apirestv1assetfamiliescodeTarget
        """
        if target is None:
            raise ValueError("Invalid value for `target`, must not be `None`")  # noqa: E501

        self._target = target

    @property
    def operations(self):
        """Gets the operations of this Apirestv1assetfamiliescodeTransformations.  # noqa: E501


        :return: The operations of this Apirestv1assetfamiliescodeTransformations.  # noqa: E501
        :rtype: Apirestv1assetfamiliescodeOperations
        """
        return self._operations

    @operations.setter
    def operations(self, operations):
        """Sets the operations of this Apirestv1assetfamiliescodeTransformations.


        :param operations: The operations of this Apirestv1assetfamiliescodeTransformations.  # noqa: E501
        :type: Apirestv1assetfamiliescodeOperations
        """
        if operations is None:
            raise ValueError("Invalid value for `operations`, must not be `None`")  # noqa: E501

        self._operations = operations

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Apirestv1assetfamiliescodeTransformations, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Apirestv1assetfamiliescodeTransformations):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
