# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Apirestv1assetfamiliescodeNamingConvention(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'source': 'object',
        'pattern': 'str',
        'abort_asset_creation_on_error': 'bool'
    }

    attribute_map = {
        'source': 'source',
        'pattern': 'pattern',
        'abort_asset_creation_on_error': 'abort_asset_creation_on_error'
    }

    def __init__(self, source=None, pattern=None, abort_asset_creation_on_error=None):  # noqa: E501
        """Apirestv1assetfamiliescodeNamingConvention - a model defined in Swagger"""  # noqa: E501
        self._source = None
        self._pattern = None
        self._abort_asset_creation_on_error = None
        self.discriminator = None
        if source is not None:
            self.source = source
        if pattern is not None:
            self.pattern = pattern
        if abort_asset_creation_on_error is not None:
            self.abort_asset_creation_on_error = abort_asset_creation_on_error

    @property
    def source(self):
        """Gets the source of this Apirestv1assetfamiliescodeNamingConvention.  # noqa: E501

        The string on which the naming convention should be applied. More details <a href='/concepts/asset-manager.html#source'>here</a>.  # noqa: E501

        :return: The source of this Apirestv1assetfamiliescodeNamingConvention.  # noqa: E501
        :rtype: object
        """
        return self._source

    @source.setter
    def source(self, source):
        """Sets the source of this Apirestv1assetfamiliescodeNamingConvention.

        The string on which the naming convention should be applied. More details <a href='/concepts/asset-manager.html#source'>here</a>.  # noqa: E501

        :param source: The source of this Apirestv1assetfamiliescodeNamingConvention.  # noqa: E501
        :type: object
        """

        self._source = source

    @property
    def pattern(self):
        """Gets the pattern of this Apirestv1assetfamiliescodeNamingConvention.  # noqa: E501

        The regular expression that should be applied on the source. More details <a href='/concepts/asset-manager.html#pattern'>here</a>.  # noqa: E501

        :return: The pattern of this Apirestv1assetfamiliescodeNamingConvention.  # noqa: E501
        :rtype: str
        """
        return self._pattern

    @pattern.setter
    def pattern(self, pattern):
        """Sets the pattern of this Apirestv1assetfamiliescodeNamingConvention.

        The regular expression that should be applied on the source. More details <a href='/concepts/asset-manager.html#pattern'>here</a>.  # noqa: E501

        :param pattern: The pattern of this Apirestv1assetfamiliescodeNamingConvention.  # noqa: E501
        :type: str
        """

        self._pattern = pattern

    @property
    def abort_asset_creation_on_error(self):
        """Gets the abort_asset_creation_on_error of this Apirestv1assetfamiliescodeNamingConvention.  # noqa: E501

        Whether the asset should be created if the naming convention failed to apply. More details <a href='/concepts/asset-manager.html#abort-asset-creation-on-error'>here</a>.  # noqa: E501

        :return: The abort_asset_creation_on_error of this Apirestv1assetfamiliescodeNamingConvention.  # noqa: E501
        :rtype: bool
        """
        return self._abort_asset_creation_on_error

    @abort_asset_creation_on_error.setter
    def abort_asset_creation_on_error(self, abort_asset_creation_on_error):
        """Sets the abort_asset_creation_on_error of this Apirestv1assetfamiliescodeNamingConvention.

        Whether the asset should be created if the naming convention failed to apply. More details <a href='/concepts/asset-manager.html#abort-asset-creation-on-error'>here</a>.  # noqa: E501

        :param abort_asset_creation_on_error: The abort_asset_creation_on_error of this Apirestv1assetfamiliescodeNamingConvention.  # noqa: E501
        :type: bool
        """

        self._abort_asset_creation_on_error = abort_asset_creation_on_error

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Apirestv1assetfamiliescodeNamingConvention, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Apirestv1assetfamiliescodeNamingConvention):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
