# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Apirestv1assetfamiliescodeOperationsParameters(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'colorspace': 'str',
        'width': 'int',
        'height': 'int',
        'ratio': 'int',
        'resolution_unit': 'str',
        'resolution_x': 'int',
        'resolution_y': 'int',
        'quality': 'int'
    }

    attribute_map = {
        'colorspace': 'colorspace',
        'width': 'width',
        'height': 'height',
        'ratio': 'ratio',
        'resolution_unit': 'resolution-unit',
        'resolution_x': 'resolution-x',
        'resolution_y': 'resolution-y',
        'quality': 'quality'
    }

    def __init__(self, colorspace=None, width=None, height=None, ratio=None, resolution_unit=None, resolution_x=None, resolution_y=None, quality=None):  # noqa: E501
        """Apirestv1assetfamiliescodeOperationsParameters - a model defined in Swagger"""  # noqa: E501
        self._colorspace = None
        self._width = None
        self._height = None
        self._ratio = None
        self._resolution_unit = None
        self._resolution_x = None
        self._resolution_y = None
        self._quality = None
        self.discriminator = None
        if colorspace is not None:
            self.colorspace = colorspace
        if width is not None:
            self.width = width
        if height is not None:
            self.height = height
        if ratio is not None:
            self.ratio = ratio
        if resolution_unit is not None:
            self.resolution_unit = resolution_unit
        if resolution_x is not None:
            self.resolution_x = resolution_x
        if resolution_y is not None:
            self.resolution_y = resolution_y
        if quality is not None:
            self.quality = quality

    @property
    def colorspace(self):
        """Gets the colorspace of this Apirestv1assetfamiliescodeOperationsParameters.  # noqa: E501


        :return: The colorspace of this Apirestv1assetfamiliescodeOperationsParameters.  # noqa: E501
        :rtype: str
        """
        return self._colorspace

    @colorspace.setter
    def colorspace(self, colorspace):
        """Sets the colorspace of this Apirestv1assetfamiliescodeOperationsParameters.


        :param colorspace: The colorspace of this Apirestv1assetfamiliescodeOperationsParameters.  # noqa: E501
        :type: str
        """

        self._colorspace = colorspace

    @property
    def width(self):
        """Gets the width of this Apirestv1assetfamiliescodeOperationsParameters.  # noqa: E501


        :return: The width of this Apirestv1assetfamiliescodeOperationsParameters.  # noqa: E501
        :rtype: int
        """
        return self._width

    @width.setter
    def width(self, width):
        """Sets the width of this Apirestv1assetfamiliescodeOperationsParameters.


        :param width: The width of this Apirestv1assetfamiliescodeOperationsParameters.  # noqa: E501
        :type: int
        """

        self._width = width

    @property
    def height(self):
        """Gets the height of this Apirestv1assetfamiliescodeOperationsParameters.  # noqa: E501


        :return: The height of this Apirestv1assetfamiliescodeOperationsParameters.  # noqa: E501
        :rtype: int
        """
        return self._height

    @height.setter
    def height(self, height):
        """Sets the height of this Apirestv1assetfamiliescodeOperationsParameters.


        :param height: The height of this Apirestv1assetfamiliescodeOperationsParameters.  # noqa: E501
        :type: int
        """

        self._height = height

    @property
    def ratio(self):
        """Gets the ratio of this Apirestv1assetfamiliescodeOperationsParameters.  # noqa: E501


        :return: The ratio of this Apirestv1assetfamiliescodeOperationsParameters.  # noqa: E501
        :rtype: int
        """
        return self._ratio

    @ratio.setter
    def ratio(self, ratio):
        """Sets the ratio of this Apirestv1assetfamiliescodeOperationsParameters.


        :param ratio: The ratio of this Apirestv1assetfamiliescodeOperationsParameters.  # noqa: E501
        :type: int
        """

        self._ratio = ratio

    @property
    def resolution_unit(self):
        """Gets the resolution_unit of this Apirestv1assetfamiliescodeOperationsParameters.  # noqa: E501


        :return: The resolution_unit of this Apirestv1assetfamiliescodeOperationsParameters.  # noqa: E501
        :rtype: str
        """
        return self._resolution_unit

    @resolution_unit.setter
    def resolution_unit(self, resolution_unit):
        """Sets the resolution_unit of this Apirestv1assetfamiliescodeOperationsParameters.


        :param resolution_unit: The resolution_unit of this Apirestv1assetfamiliescodeOperationsParameters.  # noqa: E501
        :type: str
        """

        self._resolution_unit = resolution_unit

    @property
    def resolution_x(self):
        """Gets the resolution_x of this Apirestv1assetfamiliescodeOperationsParameters.  # noqa: E501


        :return: The resolution_x of this Apirestv1assetfamiliescodeOperationsParameters.  # noqa: E501
        :rtype: int
        """
        return self._resolution_x

    @resolution_x.setter
    def resolution_x(self, resolution_x):
        """Sets the resolution_x of this Apirestv1assetfamiliescodeOperationsParameters.


        :param resolution_x: The resolution_x of this Apirestv1assetfamiliescodeOperationsParameters.  # noqa: E501
        :type: int
        """

        self._resolution_x = resolution_x

    @property
    def resolution_y(self):
        """Gets the resolution_y of this Apirestv1assetfamiliescodeOperationsParameters.  # noqa: E501


        :return: The resolution_y of this Apirestv1assetfamiliescodeOperationsParameters.  # noqa: E501
        :rtype: int
        """
        return self._resolution_y

    @resolution_y.setter
    def resolution_y(self, resolution_y):
        """Sets the resolution_y of this Apirestv1assetfamiliescodeOperationsParameters.


        :param resolution_y: The resolution_y of this Apirestv1assetfamiliescodeOperationsParameters.  # noqa: E501
        :type: int
        """

        self._resolution_y = resolution_y

    @property
    def quality(self):
        """Gets the quality of this Apirestv1assetfamiliescodeOperationsParameters.  # noqa: E501


        :return: The quality of this Apirestv1assetfamiliescodeOperationsParameters.  # noqa: E501
        :rtype: int
        """
        return self._quality

    @quality.setter
    def quality(self, quality):
        """Sets the quality of this Apirestv1assetfamiliescodeOperationsParameters.


        :param quality: The quality of this Apirestv1assetfamiliescodeOperationsParameters.  # noqa: E501
        :type: int
        """

        self._quality = quality

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Apirestv1assetfamiliescodeOperationsParameters, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Apirestv1assetfamiliescodeOperationsParameters):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
