# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Apirestv1assetfamiliescodeAssignAssetsTo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'attribute': 'str',
        'locale': 'str',
        'channel': 'str',
        'mode': 'str'
    }

    attribute_map = {
        'attribute': 'attribute',
        'locale': 'locale',
        'channel': 'channel',
        'mode': 'mode'
    }

    def __init__(self, attribute=None, locale=None, channel=None, mode=None):  # noqa: E501
        """Apirestv1assetfamiliescodeAssignAssetsTo - a model defined in Swagger"""  # noqa: E501
        self._attribute = None
        self._locale = None
        self._channel = None
        self._mode = None
        self.discriminator = None
        self.attribute = attribute
        if locale is not None:
            self.locale = locale
        if channel is not None:
            self.channel = channel
        self.mode = mode

    @property
    def attribute(self):
        """Gets the attribute of this Apirestv1assetfamiliescodeAssignAssetsTo.  # noqa: E501


        :return: The attribute of this Apirestv1assetfamiliescodeAssignAssetsTo.  # noqa: E501
        :rtype: str
        """
        return self._attribute

    @attribute.setter
    def attribute(self, attribute):
        """Sets the attribute of this Apirestv1assetfamiliescodeAssignAssetsTo.


        :param attribute: The attribute of this Apirestv1assetfamiliescodeAssignAssetsTo.  # noqa: E501
        :type: str
        """
        if attribute is None:
            raise ValueError("Invalid value for `attribute`, must not be `None`")  # noqa: E501

        self._attribute = attribute

    @property
    def locale(self):
        """Gets the locale of this Apirestv1assetfamiliescodeAssignAssetsTo.  # noqa: E501


        :return: The locale of this Apirestv1assetfamiliescodeAssignAssetsTo.  # noqa: E501
        :rtype: str
        """
        return self._locale

    @locale.setter
    def locale(self, locale):
        """Sets the locale of this Apirestv1assetfamiliescodeAssignAssetsTo.


        :param locale: The locale of this Apirestv1assetfamiliescodeAssignAssetsTo.  # noqa: E501
        :type: str
        """

        self._locale = locale

    @property
    def channel(self):
        """Gets the channel of this Apirestv1assetfamiliescodeAssignAssetsTo.  # noqa: E501


        :return: The channel of this Apirestv1assetfamiliescodeAssignAssetsTo.  # noqa: E501
        :rtype: str
        """
        return self._channel

    @channel.setter
    def channel(self, channel):
        """Sets the channel of this Apirestv1assetfamiliescodeAssignAssetsTo.


        :param channel: The channel of this Apirestv1assetfamiliescodeAssignAssetsTo.  # noqa: E501
        :type: str
        """

        self._channel = channel

    @property
    def mode(self):
        """Gets the mode of this Apirestv1assetfamiliescodeAssignAssetsTo.  # noqa: E501


        :return: The mode of this Apirestv1assetfamiliescodeAssignAssetsTo.  # noqa: E501
        :rtype: str
        """
        return self._mode

    @mode.setter
    def mode(self, mode):
        """Sets the mode of this Apirestv1assetfamiliescodeAssignAssetsTo.


        :param mode: The mode of this Apirestv1assetfamiliescodeAssignAssetsTo.  # noqa: E501
        :type: str
        """
        if mode is None:
            raise ValueError("Invalid value for `mode`, must not be `None`")  # noqa: E501

        self._mode = mode

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Apirestv1assetfamiliescodeAssignAssetsTo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Apirestv1assetfamiliescodeAssignAssetsTo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
