# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Apirestv1categoriesValuesAttributeCodeattributeUuidchannelCodelocaleCode(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'data': 'object',
        'type': 'str',
        'locale': 'str',
        'channel': 'str',
        'attribute_code': 'str'
    }

    attribute_map = {
        'data': 'data',
        'type': 'type',
        'locale': 'locale',
        'channel': 'channel',
        'attribute_code': 'attribute_code'
    }

    def __init__(self, data=None, type=None, locale=None, channel=None, attribute_code=None):  # noqa: E501
        """Apirestv1categoriesValuesAttributeCodeattributeUuidchannelCodelocaleCode - a model defined in Swagger"""  # noqa: E501
        self._data = None
        self._type = None
        self._locale = None
        self._channel = None
        self._attribute_code = None
        self.discriminator = None
        if data is not None:
            self.data = data
        if type is not None:
            self.type = type
        if locale is not None:
            self.locale = locale
        if channel is not None:
            self.channel = channel
        if attribute_code is not None:
            self.attribute_code = attribute_code

    @property
    def data(self):
        """Gets the data of this Apirestv1categoriesValuesAttributeCodeattributeUuidchannelCodelocaleCode.  # noqa: E501

        Attribute value  # noqa: E501

        :return: The data of this Apirestv1categoriesValuesAttributeCodeattributeUuidchannelCodelocaleCode.  # noqa: E501
        :rtype: object
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this Apirestv1categoriesValuesAttributeCodeattributeUuidchannelCodelocaleCode.

        Attribute value  # noqa: E501

        :param data: The data of this Apirestv1categoriesValuesAttributeCodeattributeUuidchannelCodelocaleCode.  # noqa: E501
        :type: object
        """

        self._data = data

    @property
    def type(self):
        """Gets the type of this Apirestv1categoriesValuesAttributeCodeattributeUuidchannelCodelocaleCode.  # noqa: E501

        The attribute type  # noqa: E501

        :return: The type of this Apirestv1categoriesValuesAttributeCodeattributeUuidchannelCodelocaleCode.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Apirestv1categoriesValuesAttributeCodeattributeUuidchannelCodelocaleCode.

        The attribute type  # noqa: E501

        :param type: The type of this Apirestv1categoriesValuesAttributeCodeattributeUuidchannelCodelocaleCode.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def locale(self):
        """Gets the locale of this Apirestv1categoriesValuesAttributeCodeattributeUuidchannelCodelocaleCode.  # noqa: E501

        <a href='api-reference.html#Locale'>Locale</a> code of the attribute value  # noqa: E501

        :return: The locale of this Apirestv1categoriesValuesAttributeCodeattributeUuidchannelCodelocaleCode.  # noqa: E501
        :rtype: str
        """
        return self._locale

    @locale.setter
    def locale(self, locale):
        """Sets the locale of this Apirestv1categoriesValuesAttributeCodeattributeUuidchannelCodelocaleCode.

        <a href='api-reference.html#Locale'>Locale</a> code of the attribute value  # noqa: E501

        :param locale: The locale of this Apirestv1categoriesValuesAttributeCodeattributeUuidchannelCodelocaleCode.  # noqa: E501
        :type: str
        """

        self._locale = locale

    @property
    def channel(self):
        """Gets the channel of this Apirestv1categoriesValuesAttributeCodeattributeUuidchannelCodelocaleCode.  # noqa: E501

        <a href='api-reference.html#Channel'>Channel</a> code of the attribute value  # noqa: E501

        :return: The channel of this Apirestv1categoriesValuesAttributeCodeattributeUuidchannelCodelocaleCode.  # noqa: E501
        :rtype: str
        """
        return self._channel

    @channel.setter
    def channel(self, channel):
        """Sets the channel of this Apirestv1categoriesValuesAttributeCodeattributeUuidchannelCodelocaleCode.

        <a href='api-reference.html#Channel'>Channel</a> code of the attribute value  # noqa: E501

        :param channel: The channel of this Apirestv1categoriesValuesAttributeCodeattributeUuidchannelCodelocaleCode.  # noqa: E501
        :type: str
        """

        self._channel = channel

    @property
    def attribute_code(self):
        """Gets the attribute_code of this Apirestv1categoriesValuesAttributeCodeattributeUuidchannelCodelocaleCode.  # noqa: E501

        The attribute code with its uuid (attributeCode|attributeUuid)  # noqa: E501

        :return: The attribute_code of this Apirestv1categoriesValuesAttributeCodeattributeUuidchannelCodelocaleCode.  # noqa: E501
        :rtype: str
        """
        return self._attribute_code

    @attribute_code.setter
    def attribute_code(self, attribute_code):
        """Sets the attribute_code of this Apirestv1categoriesValuesAttributeCodeattributeUuidchannelCodelocaleCode.

        The attribute code with its uuid (attributeCode|attributeUuid)  # noqa: E501

        :param attribute_code: The attribute_code of this Apirestv1categoriesValuesAttributeCodeattributeUuidchannelCodelocaleCode.  # noqa: E501
        :type: str
        """

        self._attribute_code = attribute_code

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Apirestv1categoriesValuesAttributeCodeattributeUuidchannelCodelocaleCode, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Apirestv1categoriesValuesAttributeCodeattributeUuidchannelCodelocaleCode):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
