# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Apirestv1productsuuidQuantifiedAssociationsQuantifiedAssociationTypeCode(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'products': 'list[Apirestv1productsuuidQuantifiedAssociationsQuantifiedAssociationTypeCodeProducts]',
        'product_models': 'list[Apirestv1productsQuantifiedAssociationsQuantifiedAssociationTypeCodeProductModels]'
    }

    attribute_map = {
        'products': 'products',
        'product_models': 'product_models'
    }

    def __init__(self, products=None, product_models=None):  # noqa: E501
        """Apirestv1productsuuidQuantifiedAssociationsQuantifiedAssociationTypeCode - a model defined in Swagger"""  # noqa: E501
        self._products = None
        self._product_models = None
        self.discriminator = None
        if products is not None:
            self.products = products
        if product_models is not None:
            self.product_models = product_models

    @property
    def products(self):
        """Gets the products of this Apirestv1productsuuidQuantifiedAssociationsQuantifiedAssociationTypeCode.  # noqa: E501

        Array of objects containing product uuids and quantities with which the product is in relation  # noqa: E501

        :return: The products of this Apirestv1productsuuidQuantifiedAssociationsQuantifiedAssociationTypeCode.  # noqa: E501
        :rtype: list[Apirestv1productsuuidQuantifiedAssociationsQuantifiedAssociationTypeCodeProducts]
        """
        return self._products

    @products.setter
    def products(self, products):
        """Sets the products of this Apirestv1productsuuidQuantifiedAssociationsQuantifiedAssociationTypeCode.

        Array of objects containing product uuids and quantities with which the product is in relation  # noqa: E501

        :param products: The products of this Apirestv1productsuuidQuantifiedAssociationsQuantifiedAssociationTypeCode.  # noqa: E501
        :type: list[Apirestv1productsuuidQuantifiedAssociationsQuantifiedAssociationTypeCodeProducts]
        """

        self._products = products

    @property
    def product_models(self):
        """Gets the product_models of this Apirestv1productsuuidQuantifiedAssociationsQuantifiedAssociationTypeCode.  # noqa: E501

        Array of objects containing product model codes and quantities with which the product is in relation  # noqa: E501

        :return: The product_models of this Apirestv1productsuuidQuantifiedAssociationsQuantifiedAssociationTypeCode.  # noqa: E501
        :rtype: list[Apirestv1productsQuantifiedAssociationsQuantifiedAssociationTypeCodeProductModels]
        """
        return self._product_models

    @product_models.setter
    def product_models(self, product_models):
        """Sets the product_models of this Apirestv1productsuuidQuantifiedAssociationsQuantifiedAssociationTypeCode.

        Array of objects containing product model codes and quantities with which the product is in relation  # noqa: E501

        :param product_models: The product_models of this Apirestv1productsuuidQuantifiedAssociationsQuantifiedAssociationTypeCode.  # noqa: E501
        :type: list[Apirestv1productsQuantifiedAssociationsQuantifiedAssociationTypeCodeProductModels]
        """

        self._product_models = product_models

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Apirestv1productsuuidQuantifiedAssociationsQuantifiedAssociationTypeCode, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Apirestv1productsuuidQuantifiedAssociationsQuantifiedAssociationTypeCode):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
