# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Apirestv1familiesfamilyCodevariantsVariantAttributeSets(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'level': 'int',
        'axes': 'list[str]',
        'attributes': 'list[str]'
    }

    attribute_map = {
        'level': 'level',
        'axes': 'axes',
        'attributes': 'attributes'
    }

    def __init__(self, level=None, axes=None, attributes=None):  # noqa: E501
        """Apirestv1familiesfamilyCodevariantsVariantAttributeSets - a model defined in Swagger"""  # noqa: E501
        self._level = None
        self._axes = None
        self._attributes = None
        self.discriminator = None
        self.level = level
        self.axes = axes
        if attributes is not None:
            self.attributes = attributes

    @property
    def level(self):
        """Gets the level of this Apirestv1familiesfamilyCodevariantsVariantAttributeSets.  # noqa: E501

        Enrichment level  # noqa: E501

        :return: The level of this Apirestv1familiesfamilyCodevariantsVariantAttributeSets.  # noqa: E501
        :rtype: int
        """
        return self._level

    @level.setter
    def level(self, level):
        """Sets the level of this Apirestv1familiesfamilyCodevariantsVariantAttributeSets.

        Enrichment level  # noqa: E501

        :param level: The level of this Apirestv1familiesfamilyCodevariantsVariantAttributeSets.  # noqa: E501
        :type: int
        """
        if level is None:
            raise ValueError("Invalid value for `level`, must not be `None`")  # noqa: E501

        self._level = level

    @property
    def axes(self):
        """Gets the axes of this Apirestv1familiesfamilyCodevariantsVariantAttributeSets.  # noqa: E501

        Codes of attributes used as variant axes  # noqa: E501

        :return: The axes of this Apirestv1familiesfamilyCodevariantsVariantAttributeSets.  # noqa: E501
        :rtype: list[str]
        """
        return self._axes

    @axes.setter
    def axes(self, axes):
        """Sets the axes of this Apirestv1familiesfamilyCodevariantsVariantAttributeSets.

        Codes of attributes used as variant axes  # noqa: E501

        :param axes: The axes of this Apirestv1familiesfamilyCodevariantsVariantAttributeSets.  # noqa: E501
        :type: list[str]
        """
        if axes is None:
            raise ValueError("Invalid value for `axes`, must not be `None`")  # noqa: E501

        self._axes = axes

    @property
    def attributes(self):
        """Gets the attributes of this Apirestv1familiesfamilyCodevariantsVariantAttributeSets.  # noqa: E501

        Codes of attributes bind to this enrichment level  # noqa: E501

        :return: The attributes of this Apirestv1familiesfamilyCodevariantsVariantAttributeSets.  # noqa: E501
        :rtype: list[str]
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes):
        """Sets the attributes of this Apirestv1familiesfamilyCodevariantsVariantAttributeSets.

        Codes of attributes bind to this enrichment level  # noqa: E501

        :param attributes: The attributes of this Apirestv1familiesfamilyCodevariantsVariantAttributeSets.  # noqa: E501
        :type: list[str]
        """

        self._attributes = attributes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Apirestv1familiesfamilyCodevariantsVariantAttributeSets, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Apirestv1familiesfamilyCodevariantsVariantAttributeSets):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
