# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Apirestv1productsuuidQuantifiedAssociations(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'quantified_association_type_code': 'Apirestv1productsuuidQuantifiedAssociationsQuantifiedAssociationTypeCode'
    }

    attribute_map = {
        'quantified_association_type_code': 'quantifiedAssociationTypeCode'
    }

    def __init__(self, quantified_association_type_code=None):  # noqa: E501
        """Apirestv1productsuuidQuantifiedAssociations - a model defined in Swagger"""  # noqa: E501
        self._quantified_association_type_code = None
        self.discriminator = None
        if quantified_association_type_code is not None:
            self.quantified_association_type_code = quantified_association_type_code

    @property
    def quantified_association_type_code(self):
        """Gets the quantified_association_type_code of this Apirestv1productsuuidQuantifiedAssociations.  # noqa: E501


        :return: The quantified_association_type_code of this Apirestv1productsuuidQuantifiedAssociations.  # noqa: E501
        :rtype: Apirestv1productsuuidQuantifiedAssociationsQuantifiedAssociationTypeCode
        """
        return self._quantified_association_type_code

    @quantified_association_type_code.setter
    def quantified_association_type_code(self, quantified_association_type_code):
        """Sets the quantified_association_type_code of this Apirestv1productsuuidQuantifiedAssociations.


        :param quantified_association_type_code: The quantified_association_type_code of this Apirestv1productsuuidQuantifiedAssociations.  # noqa: E501
        :type: Apirestv1productsuuidQuantifiedAssociationsQuantifiedAssociationTypeCode
        """

        self._quantified_association_type_code = quantified_association_type_code

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Apirestv1productsuuidQuantifiedAssociations, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Apirestv1productsuuidQuantifiedAssociations):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
