# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Apirestv1measurementfamiliesErrors(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        '_property': 'str',
        'message': 'str'
    }

    attribute_map = {
        '_property': 'property',
        'message': 'message'
    }

    def __init__(self, _property=None, message=None):  # noqa: E501
        """Apirestv1measurementfamiliesErrors - a model defined in Swagger"""  # noqa: E501
        self.__property = None
        self._message = None
        self.discriminator = None
        if _property is not None:
            self._property = _property
        if message is not None:
            self.message = message

    @property
    def _property(self):
        """Gets the _property of this Apirestv1measurementfamiliesErrors.  # noqa: E501


        :return: The _property of this Apirestv1measurementfamiliesErrors.  # noqa: E501
        :rtype: str
        """
        return self.__property

    @_property.setter
    def _property(self, _property):
        """Sets the _property of this Apirestv1measurementfamiliesErrors.


        :param _property: The _property of this Apirestv1measurementfamiliesErrors.  # noqa: E501
        :type: str
        """

        self.__property = _property

    @property
    def message(self):
        """Gets the message of this Apirestv1measurementfamiliesErrors.  # noqa: E501


        :return: The message of this Apirestv1measurementfamiliesErrors.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this Apirestv1measurementfamiliesErrors.


        :param message: The message of this Apirestv1measurementfamiliesErrors.  # noqa: E501
        :type: str
        """

        self._message = message

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Apirestv1measurementfamiliesErrors, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Apirestv1measurementfamiliesErrors):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
