# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Apirestv1productmodelsValues(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'attribute_code': 'list[Apirestv1productmodelsValuesAttributeCode]'
    }

    attribute_map = {
        'attribute_code': 'attributeCode'
    }

    def __init__(self, attribute_code=None):  # noqa: E501
        """Apirestv1productmodelsValues - a model defined in Swagger"""  # noqa: E501
        self._attribute_code = None
        self.discriminator = None
        if attribute_code is not None:
            self.attribute_code = attribute_code

    @property
    def attribute_code(self):
        """Gets the attribute_code of this Apirestv1productmodelsValues.  # noqa: E501


        :return: The attribute_code of this Apirestv1productmodelsValues.  # noqa: E501
        :rtype: list[Apirestv1productmodelsValuesAttributeCode]
        """
        return self._attribute_code

    @attribute_code.setter
    def attribute_code(self, attribute_code):
        """Sets the attribute_code of this Apirestv1productmodelsValues.


        :param attribute_code: The attribute_code of this Apirestv1productmodelsValues.  # noqa: E501
        :type: list[Apirestv1productmodelsValuesAttributeCode]
        """

        self._attribute_code = attribute_code

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Apirestv1productmodelsValues, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Apirestv1productmodelsValues):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
