# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Apirestv1productmodelsMetadata(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'workflow_status': 'str'
    }

    attribute_map = {
        'workflow_status': 'workflow_status'
    }

    def __init__(self, workflow_status=None):  # noqa: E501
        """Apirestv1productmodelsMetadata - a model defined in Swagger"""  # noqa: E501
        self._workflow_status = None
        self.discriminator = None
        if workflow_status is not None:
            self.workflow_status = workflow_status

    @property
    def workflow_status(self):
        """Gets the workflow_status of this Apirestv1productmodelsMetadata.  # noqa: E501

        Status of the product model regarding the user permissions  # noqa: E501

        :return: The workflow_status of this Apirestv1productmodelsMetadata.  # noqa: E501
        :rtype: str
        """
        return self._workflow_status

    @workflow_status.setter
    def workflow_status(self, workflow_status):
        """Sets the workflow_status of this Apirestv1productmodelsMetadata.

        Status of the product model regarding the user permissions  # noqa: E501

        :param workflow_status: The workflow_status of this Apirestv1productmodelsMetadata.  # noqa: E501
        :type: str
        """
        allowed_values = ["read_only", "draft_in_progress", "proposal_waiting_for_approval", "working_copy"]  # noqa: E501
        if workflow_status not in allowed_values:
            raise ValueError(
                "Invalid value for `workflow_status` ({0}), must be one of {1}"  # noqa: E501
                .format(workflow_status, allowed_values)
            )

        self._workflow_status = workflow_status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Apirestv1productmodelsMetadata, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Apirestv1productmodelsMetadata):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
