# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AssociationTypes(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'links': 'PaginationLinks',
        'current_page': 'int'
    }

    attribute_map = {
        'links': '_links',
        'current_page': 'current_page'
    }

    def __init__(self, links=None, current_page=None):  # noqa: E501
        """AssociationTypes - a model defined in Swagger"""  # noqa: E501
        self._links = None
        self._current_page = None
        self.discriminator = None
        if links is not None:
            self.links = links
        if current_page is not None:
            self.current_page = current_page

    @property
    def links(self):
        """Gets the links of this AssociationTypes.  # noqa: E501


        :return: The links of this AssociationTypes.  # noqa: E501
        :rtype: PaginationLinks
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this AssociationTypes.


        :param links: The links of this AssociationTypes.  # noqa: E501
        :type: PaginationLinks
        """

        self._links = links

    @property
    def current_page(self):
        """Gets the current_page of this AssociationTypes.  # noqa: E501

        Current page number  # noqa: E501

        :return: The current_page of this AssociationTypes.  # noqa: E501
        :rtype: int
        """
        return self._current_page

    @current_page.setter
    def current_page(self, current_page):
        """Sets the current_page of this AssociationTypes.

        Current page number  # noqa: E501

        :param current_page: The current_page of this AssociationTypes.  # noqa: E501
        :type: int
        """

        self._current_page = current_page

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AssociationTypes, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AssociationTypes):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
