# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Family(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'code': 'str',
        'attribute_as_label': 'str',
        'attribute_as_image': 'str',
        'attributes': 'list[str]',
        'attribute_requirements': 'Apirestv1familiesAttributeRequirements',
        'labels': 'Apirestv1familiesLabels'
    }

    attribute_map = {
        'code': 'code',
        'attribute_as_label': 'attribute_as_label',
        'attribute_as_image': 'attribute_as_image',
        'attributes': 'attributes',
        'attribute_requirements': 'attribute_requirements',
        'labels': 'labels'
    }

    def __init__(self, code=None, attribute_as_label=None, attribute_as_image=None, attributes=None, attribute_requirements=None, labels=None):  # noqa: E501
        """Family - a model defined in Swagger"""  # noqa: E501
        self._code = None
        self._attribute_as_label = None
        self._attribute_as_image = None
        self._attributes = None
        self._attribute_requirements = None
        self._labels = None
        self.discriminator = None
        self.code = code
        self.attribute_as_label = attribute_as_label
        if attribute_as_image is not None:
            self.attribute_as_image = attribute_as_image
        if attributes is not None:
            self.attributes = attributes
        if attribute_requirements is not None:
            self.attribute_requirements = attribute_requirements
        if labels is not None:
            self.labels = labels

    @property
    def code(self):
        """Gets the code of this Family.  # noqa: E501

        Family code  # noqa: E501

        :return: The code of this Family.  # noqa: E501
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this Family.

        Family code  # noqa: E501

        :param code: The code of this Family.  # noqa: E501
        :type: str
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")  # noqa: E501

        self._code = code

    @property
    def attribute_as_label(self):
        """Gets the attribute_as_label of this Family.  # noqa: E501

        Attribute code used as label  # noqa: E501

        :return: The attribute_as_label of this Family.  # noqa: E501
        :rtype: str
        """
        return self._attribute_as_label

    @attribute_as_label.setter
    def attribute_as_label(self, attribute_as_label):
        """Sets the attribute_as_label of this Family.

        Attribute code used as label  # noqa: E501

        :param attribute_as_label: The attribute_as_label of this Family.  # noqa: E501
        :type: str
        """
        if attribute_as_label is None:
            raise ValueError("Invalid value for `attribute_as_label`, must not be `None`")  # noqa: E501

        self._attribute_as_label = attribute_as_label

    @property
    def attribute_as_image(self):
        """Gets the attribute_as_image of this Family.  # noqa: E501

        Attribute code used as the main picture in the user interface (only since v2.0)  # noqa: E501

        :return: The attribute_as_image of this Family.  # noqa: E501
        :rtype: str
        """
        return self._attribute_as_image

    @attribute_as_image.setter
    def attribute_as_image(self, attribute_as_image):
        """Sets the attribute_as_image of this Family.

        Attribute code used as the main picture in the user interface (only since v2.0)  # noqa: E501

        :param attribute_as_image: The attribute_as_image of this Family.  # noqa: E501
        :type: str
        """

        self._attribute_as_image = attribute_as_image

    @property
    def attributes(self):
        """Gets the attributes of this Family.  # noqa: E501

        Attributes codes that compose the family  # noqa: E501

        :return: The attributes of this Family.  # noqa: E501
        :rtype: list[str]
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes):
        """Sets the attributes of this Family.

        Attributes codes that compose the family  # noqa: E501

        :param attributes: The attributes of this Family.  # noqa: E501
        :type: list[str]
        """

        self._attributes = attributes

    @property
    def attribute_requirements(self):
        """Gets the attribute_requirements of this Family.  # noqa: E501


        :return: The attribute_requirements of this Family.  # noqa: E501
        :rtype: Apirestv1familiesAttributeRequirements
        """
        return self._attribute_requirements

    @attribute_requirements.setter
    def attribute_requirements(self, attribute_requirements):
        """Sets the attribute_requirements of this Family.


        :param attribute_requirements: The attribute_requirements of this Family.  # noqa: E501
        :type: Apirestv1familiesAttributeRequirements
        """

        self._attribute_requirements = attribute_requirements

    @property
    def labels(self):
        """Gets the labels of this Family.  # noqa: E501


        :return: The labels of this Family.  # noqa: E501
        :rtype: Apirestv1familiesLabels
        """
        return self._labels

    @labels.setter
    def labels(self, labels):
        """Sets the labels of this Family.


        :param labels: The labels of this Family.  # noqa: E501
        :type: Apirestv1familiesLabels
        """

        self._labels = labels

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Family, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Family):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
