# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse20039(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'host': 'str',
        'authentication': 'object',
        'routes': 'object'
    }

    attribute_map = {
        'host': 'host',
        'authentication': 'authentication',
        'routes': 'routes'
    }

    def __init__(self, host=None, authentication=None, routes=None):  # noqa: E501
        """InlineResponse20039 - a model defined in Swagger"""  # noqa: E501
        self._host = None
        self._authentication = None
        self._routes = None
        self.discriminator = None
        if host is not None:
            self.host = host
        if authentication is not None:
            self.authentication = authentication
        if routes is not None:
            self.routes = routes

    @property
    def host(self):
        """Gets the host of this InlineResponse20039.  # noqa: E501

        Host name  # noqa: E501

        :return: The host of this InlineResponse20039.  # noqa: E501
        :rtype: str
        """
        return self._host

    @host.setter
    def host(self, host):
        """Sets the host of this InlineResponse20039.

        Host name  # noqa: E501

        :param host: The host of this InlineResponse20039.  # noqa: E501
        :type: str
        """

        self._host = host

    @property
    def authentication(self):
        """Gets the authentication of this InlineResponse20039.  # noqa: E501

        Endpoint to get the authentication token  # noqa: E501

        :return: The authentication of this InlineResponse20039.  # noqa: E501
        :rtype: object
        """
        return self._authentication

    @authentication.setter
    def authentication(self, authentication):
        """Sets the authentication of this InlineResponse20039.

        Endpoint to get the authentication token  # noqa: E501

        :param authentication: The authentication of this InlineResponse20039.  # noqa: E501
        :type: object
        """

        self._authentication = authentication

    @property
    def routes(self):
        """Gets the routes of this InlineResponse20039.  # noqa: E501

        All the availables endpoints  # noqa: E501

        :return: The routes of this InlineResponse20039.  # noqa: E501
        :rtype: object
        """
        return self._routes

    @routes.setter
    def routes(self, routes):
        """Sets the routes of this InlineResponse20039.

        All the availables endpoints  # noqa: E501

        :param routes: The routes of this InlineResponse20039.  # noqa: E501
        :type: object
        """

        self._routes = routes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20039, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20039):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
