# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse20012(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'code': 'str',
        'labels': 'Apirestv1associationtypesLabels',
        'is_quantified': 'bool',
        'is_two_way': 'bool'
    }

    attribute_map = {
        'code': 'code',
        'labels': 'labels',
        'is_quantified': 'is_quantified',
        'is_two_way': 'is_two_way'
    }

    def __init__(self, code=None, labels=None, is_quantified=False, is_two_way=False):  # noqa: E501
        """InlineResponse20012 - a model defined in Swagger"""  # noqa: E501
        self._code = None
        self._labels = None
        self._is_quantified = None
        self._is_two_way = None
        self.discriminator = None
        self.code = code
        if labels is not None:
            self.labels = labels
        if is_quantified is not None:
            self.is_quantified = is_quantified
        if is_two_way is not None:
            self.is_two_way = is_two_way

    @property
    def code(self):
        """Gets the code of this InlineResponse20012.  # noqa: E501

        Association type code  # noqa: E501

        :return: The code of this InlineResponse20012.  # noqa: E501
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this InlineResponse20012.

        Association type code  # noqa: E501

        :param code: The code of this InlineResponse20012.  # noqa: E501
        :type: str
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")  # noqa: E501

        self._code = code

    @property
    def labels(self):
        """Gets the labels of this InlineResponse20012.  # noqa: E501


        :return: The labels of this InlineResponse20012.  # noqa: E501
        :rtype: Apirestv1associationtypesLabels
        """
        return self._labels

    @labels.setter
    def labels(self, labels):
        """Sets the labels of this InlineResponse20012.


        :param labels: The labels of this InlineResponse20012.  # noqa: E501
        :type: Apirestv1associationtypesLabels
        """

        self._labels = labels

    @property
    def is_quantified(self):
        """Gets the is_quantified of this InlineResponse20012.  # noqa: E501

        When true, the association is a quantified association (Only available in the PIM Serenity version.)  # noqa: E501

        :return: The is_quantified of this InlineResponse20012.  # noqa: E501
        :rtype: bool
        """
        return self._is_quantified

    @is_quantified.setter
    def is_quantified(self, is_quantified):
        """Sets the is_quantified of this InlineResponse20012.

        When true, the association is a quantified association (Only available in the PIM Serenity version.)  # noqa: E501

        :param is_quantified: The is_quantified of this InlineResponse20012.  # noqa: E501
        :type: bool
        """

        self._is_quantified = is_quantified

    @property
    def is_two_way(self):
        """Gets the is_two_way of this InlineResponse20012.  # noqa: E501

        When true, the association is a two-way association (Only available in the PIM Serenity version.)  # noqa: E501

        :return: The is_two_way of this InlineResponse20012.  # noqa: E501
        :rtype: bool
        """
        return self._is_two_way

    @is_two_way.setter
    def is_two_way(self, is_two_way):
        """Sets the is_two_way of this InlineResponse20012.

        When true, the association is a two-way association (Only available in the PIM Serenity version.)  # noqa: E501

        :param is_two_way: The is_two_way of this InlineResponse20012.  # noqa: E501
        :type: bool
        """

        self._is_two_way = is_two_way

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20012, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20012):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
