# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MappingschemasProductBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'schema': 'str',
        'comment': 'str',
        'title': 'str',
        'description': 'str',
        'type': 'str',
        'properties': 'object'
    }

    attribute_map = {
        'id': '$id',
        'schema': '$schema',
        'comment': '$comment',
        'title': 'title',
        'description': 'description',
        'type': 'type',
        'properties': 'properties'
    }

    def __init__(self, id=None, schema=None, comment=None, title=None, description=None, type=None, properties=None):  # noqa: E501
        """MappingschemasProductBody - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._schema = None
        self._comment = None
        self._title = None
        self._description = None
        self._type = None
        self._properties = None
        self.discriminator = None
        if id is not None:
            self.id = id
        self.schema = schema
        if comment is not None:
            self.comment = comment
        if title is not None:
            self.title = title
        if description is not None:
            self.description = description
        if type is not None:
            self.type = type
        self.properties = properties

    @property
    def id(self):
        """Gets the id of this MappingschemasProductBody.  # noqa: E501

        id of your schema  # noqa: E501

        :return: The id of this MappingschemasProductBody.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this MappingschemasProductBody.

        id of your schema  # noqa: E501

        :param id: The id of this MappingschemasProductBody.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def schema(self):
        """Gets the schema of this MappingschemasProductBody.  # noqa: E501

        $schema indicates which product mapping schema version your app uses  # noqa: E501

        :return: The schema of this MappingschemasProductBody.  # noqa: E501
        :rtype: str
        """
        return self._schema

    @schema.setter
    def schema(self, schema):
        """Sets the schema of this MappingschemasProductBody.

        $schema indicates which product mapping schema version your app uses  # noqa: E501

        :param schema: The schema of this MappingschemasProductBody.  # noqa: E501
        :type: str
        """
        if schema is None:
            raise ValueError("Invalid value for `schema`, must not be `None`")  # noqa: E501

        self._schema = schema

    @property
    def comment(self):
        """Gets the comment of this MappingschemasProductBody.  # noqa: E501

        allows you to add a comment  # noqa: E501

        :return: The comment of this MappingschemasProductBody.  # noqa: E501
        :rtype: str
        """
        return self._comment

    @comment.setter
    def comment(self, comment):
        """Sets the comment of this MappingschemasProductBody.

        allows you to add a comment  # noqa: E501

        :param comment: The comment of this MappingschemasProductBody.  # noqa: E501
        :type: str
        """

        self._comment = comment

    @property
    def title(self):
        """Gets the title of this MappingschemasProductBody.  # noqa: E501

        allows you to add a title to your mapping schema  # noqa: E501

        :return: The title of this MappingschemasProductBody.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this MappingschemasProductBody.

        allows you to add a title to your mapping schema  # noqa: E501

        :param title: The title of this MappingschemasProductBody.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def description(self):
        """Gets the description of this MappingschemasProductBody.  # noqa: E501

        allows you to add a description of your mapping schema  # noqa: E501

        :return: The description of this MappingschemasProductBody.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this MappingschemasProductBody.

        allows you to add a description of your mapping schema  # noqa: E501

        :param description: The description of this MappingschemasProductBody.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def type(self):
        """Gets the type of this MappingschemasProductBody.  # noqa: E501

        should always be \"object\"  # noqa: E501

        :return: The type of this MappingschemasProductBody.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this MappingschemasProductBody.

        should always be \"object\"  # noqa: E501

        :param type: The type of this MappingschemasProductBody.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def properties(self):
        """Gets the properties of this MappingschemasProductBody.  # noqa: E501

        list and describe the targets your app expects  # noqa: E501

        :return: The properties of this MappingschemasProductBody.  # noqa: E501
        :rtype: object
        """
        return self._properties

    @properties.setter
    def properties(self, properties):
        """Sets the properties of this MappingschemasProductBody.

        list and describe the targets your app expects  # noqa: E501

        :param properties: The properties of this MappingschemasProductBody.  # noqa: E501
        :type: object
        """
        if properties is None:
            raise ValueError("Invalid value for `properties`, must not be `None`")  # noqa: E501

        self._properties = properties

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MappingschemasProductBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MappingschemasProductBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
