# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MeasureFamily(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'code': 'str',
        'standard': 'str',
        'units': 'list[MeasureFamilyUnits]'
    }

    attribute_map = {
        'code': 'code',
        'standard': 'standard',
        'units': 'units'
    }

    def __init__(self, code=None, standard=None, units=None):  # noqa: E501
        """MeasureFamily - a model defined in Swagger"""  # noqa: E501
        self._code = None
        self._standard = None
        self._units = None
        self.discriminator = None
        self.code = code
        if standard is not None:
            self.standard = standard
        if units is not None:
            self.units = units

    @property
    def code(self):
        """Gets the code of this MeasureFamily.  # noqa: E501

        Measure family code  # noqa: E501

        :return: The code of this MeasureFamily.  # noqa: E501
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this MeasureFamily.

        Measure family code  # noqa: E501

        :param code: The code of this MeasureFamily.  # noqa: E501
        :type: str
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")  # noqa: E501

        self._code = code

    @property
    def standard(self):
        """Gets the standard of this MeasureFamily.  # noqa: E501

        Measure family standard  # noqa: E501

        :return: The standard of this MeasureFamily.  # noqa: E501
        :rtype: str
        """
        return self._standard

    @standard.setter
    def standard(self, standard):
        """Sets the standard of this MeasureFamily.

        Measure family standard  # noqa: E501

        :param standard: The standard of this MeasureFamily.  # noqa: E501
        :type: str
        """

        self._standard = standard

    @property
    def units(self):
        """Gets the units of this MeasureFamily.  # noqa: E501

        Family units  # noqa: E501

        :return: The units of this MeasureFamily.  # noqa: E501
        :rtype: list[MeasureFamilyUnits]
        """
        return self._units

    @units.setter
    def units(self, units):
        """Sets the units of this MeasureFamily.

        Family units  # noqa: E501

        :param units: The units of this MeasureFamily.  # noqa: E501
        :type: list[MeasureFamilyUnits]
        """

        self._units = units

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MeasureFamily, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MeasureFamily):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
