# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ProductUuid(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'uuid': 'str',
        'enabled': 'bool',
        'family': 'str',
        'categories': 'list[str]',
        'groups': 'list[str]',
        'parent': 'str',
        'values': 'Apirestv1productsValues',
        'associations': 'Apirestv1productsuuidAssociations',
        'quantified_associations': 'Apirestv1productsuuidQuantifiedAssociations',
        'created': 'str',
        'updated': 'str',
        'metadata': 'Apirestv1productsMetadata',
        'quality_scores': 'object',
        'completenesses': 'list[Apirestv1productsCompletenesses]'
    }

    attribute_map = {
        'uuid': 'uuid',
        'enabled': 'enabled',
        'family': 'family',
        'categories': 'categories',
        'groups': 'groups',
        'parent': 'parent',
        'values': 'values',
        'associations': 'associations',
        'quantified_associations': 'quantified_associations',
        'created': 'created',
        'updated': 'updated',
        'metadata': 'metadata',
        'quality_scores': 'quality_scores',
        'completenesses': 'completenesses'
    }

    def __init__(self, uuid=None, enabled=True, family='null only in the case of a non variant product', categories=None, groups=None, parent=None, values=None, associations=None, quantified_associations=None, created=None, updated=None, metadata=None, quality_scores=None, completenesses=None):  # noqa: E501
        """ProductUuid - a model defined in Swagger"""  # noqa: E501
        self._uuid = None
        self._enabled = None
        self._family = None
        self._categories = None
        self._groups = None
        self._parent = None
        self._values = None
        self._associations = None
        self._quantified_associations = None
        self._created = None
        self._updated = None
        self._metadata = None
        self._quality_scores = None
        self._completenesses = None
        self.discriminator = None
        if uuid is not None:
            self.uuid = uuid
        if enabled is not None:
            self.enabled = enabled
        if family is not None:
            self.family = family
        if categories is not None:
            self.categories = categories
        if groups is not None:
            self.groups = groups
        if parent is not None:
            self.parent = parent
        if values is not None:
            self.values = values
        if associations is not None:
            self.associations = associations
        if quantified_associations is not None:
            self.quantified_associations = quantified_associations
        if created is not None:
            self.created = created
        if updated is not None:
            self.updated = updated
        if metadata is not None:
            self.metadata = metadata
        if quality_scores is not None:
            self.quality_scores = quality_scores
        if completenesses is not None:
            self.completenesses = completenesses

    @property
    def uuid(self):
        """Gets the uuid of this ProductUuid.  # noqa: E501

        Product uuid  # noqa: E501

        :return: The uuid of this ProductUuid.  # noqa: E501
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid):
        """Sets the uuid of this ProductUuid.

        Product uuid  # noqa: E501

        :param uuid: The uuid of this ProductUuid.  # noqa: E501
        :type: str
        """

        self._uuid = uuid

    @property
    def enabled(self):
        """Gets the enabled of this ProductUuid.  # noqa: E501

        Whether the product is enabled  # noqa: E501

        :return: The enabled of this ProductUuid.  # noqa: E501
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled):
        """Sets the enabled of this ProductUuid.

        Whether the product is enabled  # noqa: E501

        :param enabled: The enabled of this ProductUuid.  # noqa: E501
        :type: bool
        """

        self._enabled = enabled

    @property
    def family(self):
        """Gets the family of this ProductUuid.  # noqa: E501

        <a href='api-reference.html#Family'>Family</a> code from which the product inherits its attributes and attributes requirements.  # noqa: E501

        :return: The family of this ProductUuid.  # noqa: E501
        :rtype: str
        """
        return self._family

    @family.setter
    def family(self, family):
        """Sets the family of this ProductUuid.

        <a href='api-reference.html#Family'>Family</a> code from which the product inherits its attributes and attributes requirements.  # noqa: E501

        :param family: The family of this ProductUuid.  # noqa: E501
        :type: str
        """

        self._family = family

    @property
    def categories(self):
        """Gets the categories of this ProductUuid.  # noqa: E501

        Codes of the <a href='api-reference.html#Category'>categories</a> in which the product is classified  # noqa: E501

        :return: The categories of this ProductUuid.  # noqa: E501
        :rtype: list[str]
        """
        return self._categories

    @categories.setter
    def categories(self, categories):
        """Sets the categories of this ProductUuid.

        Codes of the <a href='api-reference.html#Category'>categories</a> in which the product is classified  # noqa: E501

        :param categories: The categories of this ProductUuid.  # noqa: E501
        :type: list[str]
        """

        self._categories = categories

    @property
    def groups(self):
        """Gets the groups of this ProductUuid.  # noqa: E501

        Codes of the groups to which the product belong  # noqa: E501

        :return: The groups of this ProductUuid.  # noqa: E501
        :rtype: list[str]
        """
        return self._groups

    @groups.setter
    def groups(self, groups):
        """Sets the groups of this ProductUuid.

        Codes of the groups to which the product belong  # noqa: E501

        :param groups: The groups of this ProductUuid.  # noqa: E501
        :type: list[str]
        """

        self._groups = groups

    @property
    def parent(self):
        """Gets the parent of this ProductUuid.  # noqa: E501

        Code of the parent <a href='api-reference.html#Productmodel'>product model</a> when the product is a variant (only available since the 2.0). This parent can be modified since the 2.3.  # noqa: E501

        :return: The parent of this ProductUuid.  # noqa: E501
        :rtype: str
        """
        return self._parent

    @parent.setter
    def parent(self, parent):
        """Sets the parent of this ProductUuid.

        Code of the parent <a href='api-reference.html#Productmodel'>product model</a> when the product is a variant (only available since the 2.0). This parent can be modified since the 2.3.  # noqa: E501

        :param parent: The parent of this ProductUuid.  # noqa: E501
        :type: str
        """

        self._parent = parent

    @property
    def values(self):
        """Gets the values of this ProductUuid.  # noqa: E501


        :return: The values of this ProductUuid.  # noqa: E501
        :rtype: Apirestv1productsValues
        """
        return self._values

    @values.setter
    def values(self, values):
        """Sets the values of this ProductUuid.


        :param values: The values of this ProductUuid.  # noqa: E501
        :type: Apirestv1productsValues
        """

        self._values = values

    @property
    def associations(self):
        """Gets the associations of this ProductUuid.  # noqa: E501


        :return: The associations of this ProductUuid.  # noqa: E501
        :rtype: Apirestv1productsuuidAssociations
        """
        return self._associations

    @associations.setter
    def associations(self, associations):
        """Sets the associations of this ProductUuid.


        :param associations: The associations of this ProductUuid.  # noqa: E501
        :type: Apirestv1productsuuidAssociations
        """

        self._associations = associations

    @property
    def quantified_associations(self):
        """Gets the quantified_associations of this ProductUuid.  # noqa: E501


        :return: The quantified_associations of this ProductUuid.  # noqa: E501
        :rtype: Apirestv1productsuuidQuantifiedAssociations
        """
        return self._quantified_associations

    @quantified_associations.setter
    def quantified_associations(self, quantified_associations):
        """Sets the quantified_associations of this ProductUuid.


        :param quantified_associations: The quantified_associations of this ProductUuid.  # noqa: E501
        :type: Apirestv1productsuuidQuantifiedAssociations
        """

        self._quantified_associations = quantified_associations

    @property
    def created(self):
        """Gets the created of this ProductUuid.  # noqa: E501

        Date of creation  # noqa: E501

        :return: The created of this ProductUuid.  # noqa: E501
        :rtype: str
        """
        return self._created

    @created.setter
    def created(self, created):
        """Sets the created of this ProductUuid.

        Date of creation  # noqa: E501

        :param created: The created of this ProductUuid.  # noqa: E501
        :type: str
        """

        self._created = created

    @property
    def updated(self):
        """Gets the updated of this ProductUuid.  # noqa: E501

        Date of the last update  # noqa: E501

        :return: The updated of this ProductUuid.  # noqa: E501
        :rtype: str
        """
        return self._updated

    @updated.setter
    def updated(self, updated):
        """Sets the updated of this ProductUuid.

        Date of the last update  # noqa: E501

        :param updated: The updated of this ProductUuid.  # noqa: E501
        :type: str
        """

        self._updated = updated

    @property
    def metadata(self):
        """Gets the metadata of this ProductUuid.  # noqa: E501


        :return: The metadata of this ProductUuid.  # noqa: E501
        :rtype: Apirestv1productsMetadata
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata):
        """Sets the metadata of this ProductUuid.


        :param metadata: The metadata of this ProductUuid.  # noqa: E501
        :type: Apirestv1productsMetadata
        """

        self._metadata = metadata

    @property
    def quality_scores(self):
        """Gets the quality_scores of this ProductUuid.  # noqa: E501

        Product quality scores for each channel/locale combination (only available since the 5.0 and when the \"with_quality_scores\" query parameter is set to \"true\")  # noqa: E501

        :return: The quality_scores of this ProductUuid.  # noqa: E501
        :rtype: object
        """
        return self._quality_scores

    @quality_scores.setter
    def quality_scores(self, quality_scores):
        """Sets the quality_scores of this ProductUuid.

        Product quality scores for each channel/locale combination (only available since the 5.0 and when the \"with_quality_scores\" query parameter is set to \"true\")  # noqa: E501

        :param quality_scores: The quality_scores of this ProductUuid.  # noqa: E501
        :type: object
        """

        self._quality_scores = quality_scores

    @property
    def completenesses(self):
        """Gets the completenesses of this ProductUuid.  # noqa: E501

        Product completenesses for each channel/locale combination (only available since the 7.0 version, and when the \"with_completenesses\" query parameter is set to \"true\")  # noqa: E501

        :return: The completenesses of this ProductUuid.  # noqa: E501
        :rtype: list[Apirestv1productsCompletenesses]
        """
        return self._completenesses

    @completenesses.setter
    def completenesses(self, completenesses):
        """Sets the completenesses of this ProductUuid.

        Product completenesses for each channel/locale combination (only available since the 7.0 version, and when the \"with_completenesses\" query parameter is set to \"true\")  # noqa: E501

        :param completenesses: The completenesses of this ProductUuid.  # noqa: E501
        :type: list[Apirestv1productsCompletenesses]
        """

        self._completenesses = completenesses

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProductUuid, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProductUuid):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
