# coding: utf-8

"""
    Akeneo PIM REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class V1AttributesBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'code': 'str',
        'type': 'str',
        'labels': 'Apirestv1attributesLabels',
        'group': 'str',
        'group_labels': 'Apirestv1attributesGroupLabels',
        'sort_order': 'int',
        'localizable': 'bool',
        'scopable': 'bool',
        'available_locales': 'list[str]',
        'unique': 'bool',
        'useable_as_grid_filter': 'bool',
        'max_characters': 'int',
        'validation_rule': 'str',
        'validation_regexp': 'str',
        'wysiwyg_enabled': 'bool',
        'number_min': 'str',
        'number_max': 'str',
        'decimals_allowed': 'bool',
        'negative_allowed': 'bool',
        'metric_family': 'str',
        'default_metric_unit': 'str',
        'date_min': 'datetime',
        'date_max': 'datetime',
        'allowed_extensions': 'list[str]',
        'max_file_size': 'str',
        'reference_data_name': 'str',
        'default_value': 'bool',
        'table_configuration': 'list[Apirestv1attributesTableConfiguration]'
    }

    attribute_map = {
        'code': 'code',
        'type': 'type',
        'labels': 'labels',
        'group': 'group',
        'group_labels': 'group_labels',
        'sort_order': 'sort_order',
        'localizable': 'localizable',
        'scopable': 'scopable',
        'available_locales': 'available_locales',
        'unique': 'unique',
        'useable_as_grid_filter': 'useable_as_grid_filter',
        'max_characters': 'max_characters',
        'validation_rule': 'validation_rule',
        'validation_regexp': 'validation_regexp',
        'wysiwyg_enabled': 'wysiwyg_enabled',
        'number_min': 'number_min',
        'number_max': 'number_max',
        'decimals_allowed': 'decimals_allowed',
        'negative_allowed': 'negative_allowed',
        'metric_family': 'metric_family',
        'default_metric_unit': 'default_metric_unit',
        'date_min': 'date_min',
        'date_max': 'date_max',
        'allowed_extensions': 'allowed_extensions',
        'max_file_size': 'max_file_size',
        'reference_data_name': 'reference_data_name',
        'default_value': 'default_value',
        'table_configuration': 'table_configuration'
    }

    def __init__(self, code=None, type=None, labels=None, group=None, group_labels=None, sort_order=None, localizable=False, scopable=False, available_locales=None, unique=None, useable_as_grid_filter=None, max_characters=None, validation_rule=None, validation_regexp=None, wysiwyg_enabled=None, number_min=None, number_max=None, decimals_allowed=None, negative_allowed=None, metric_family=None, default_metric_unit=None, date_min=None, date_max=None, allowed_extensions=None, max_file_size=None, reference_data_name=None, default_value=None, table_configuration=None):  # noqa: E501
        """V1AttributesBody - a model defined in Swagger"""  # noqa: E501
        self._code = None
        self._type = None
        self._labels = None
        self._group = None
        self._group_labels = None
        self._sort_order = None
        self._localizable = None
        self._scopable = None
        self._available_locales = None
        self._unique = None
        self._useable_as_grid_filter = None
        self._max_characters = None
        self._validation_rule = None
        self._validation_regexp = None
        self._wysiwyg_enabled = None
        self._number_min = None
        self._number_max = None
        self._decimals_allowed = None
        self._negative_allowed = None
        self._metric_family = None
        self._default_metric_unit = None
        self._date_min = None
        self._date_max = None
        self._allowed_extensions = None
        self._max_file_size = None
        self._reference_data_name = None
        self._default_value = None
        self._table_configuration = None
        self.discriminator = None
        self.code = code
        self.type = type
        if labels is not None:
            self.labels = labels
        self.group = group
        if group_labels is not None:
            self.group_labels = group_labels
        if sort_order is not None:
            self.sort_order = sort_order
        if localizable is not None:
            self.localizable = localizable
        if scopable is not None:
            self.scopable = scopable
        if available_locales is not None:
            self.available_locales = available_locales
        if unique is not None:
            self.unique = unique
        if useable_as_grid_filter is not None:
            self.useable_as_grid_filter = useable_as_grid_filter
        if max_characters is not None:
            self.max_characters = max_characters
        if validation_rule is not None:
            self.validation_rule = validation_rule
        if validation_regexp is not None:
            self.validation_regexp = validation_regexp
        if wysiwyg_enabled is not None:
            self.wysiwyg_enabled = wysiwyg_enabled
        if number_min is not None:
            self.number_min = number_min
        if number_max is not None:
            self.number_max = number_max
        if decimals_allowed is not None:
            self.decimals_allowed = decimals_allowed
        if negative_allowed is not None:
            self.negative_allowed = negative_allowed
        if metric_family is not None:
            self.metric_family = metric_family
        if default_metric_unit is not None:
            self.default_metric_unit = default_metric_unit
        if date_min is not None:
            self.date_min = date_min
        if date_max is not None:
            self.date_max = date_max
        if allowed_extensions is not None:
            self.allowed_extensions = allowed_extensions
        if max_file_size is not None:
            self.max_file_size = max_file_size
        if reference_data_name is not None:
            self.reference_data_name = reference_data_name
        if default_value is not None:
            self.default_value = default_value
        if table_configuration is not None:
            self.table_configuration = table_configuration

    @property
    def code(self):
        """Gets the code of this V1AttributesBody.  # noqa: E501

        Attribute code  # noqa: E501

        :return: The code of this V1AttributesBody.  # noqa: E501
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this V1AttributesBody.

        Attribute code  # noqa: E501

        :param code: The code of this V1AttributesBody.  # noqa: E501
        :type: str
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")  # noqa: E501

        self._code = code

    @property
    def type(self):
        """Gets the type of this V1AttributesBody.  # noqa: E501

        Attribute type. See <a href='/concepts/catalog-structure.html#attribute'>type</a> section for more details.  # noqa: E501

        :return: The type of this V1AttributesBody.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this V1AttributesBody.

        Attribute type. See <a href='/concepts/catalog-structure.html#attribute'>type</a> section for more details.  # noqa: E501

        :param type: The type of this V1AttributesBody.  # noqa: E501
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501
        allowed_values = ["pim_catalog_identifier", "pim_catalog_metric", "pim_catalog_number", "pim_catalog_reference_data_multi_select", "pim_catalog_reference_data_simple_select", "pim_catalog_simpleselect", "pim_catalog_multiselect", "pim_catalog_date", "pim_catalog_textarea", "pim_catalog_text", "pim_catalog_file", "pim_catalog_image", "pim_catalog_price_collection", "pim_catalog_boolean", "akeneo_reference_entity", "akeneo_reference_entity_collection", "pim_catalog_asset_collection"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def labels(self):
        """Gets the labels of this V1AttributesBody.  # noqa: E501


        :return: The labels of this V1AttributesBody.  # noqa: E501
        :rtype: Apirestv1attributesLabels
        """
        return self._labels

    @labels.setter
    def labels(self, labels):
        """Sets the labels of this V1AttributesBody.


        :param labels: The labels of this V1AttributesBody.  # noqa: E501
        :type: Apirestv1attributesLabels
        """

        self._labels = labels

    @property
    def group(self):
        """Gets the group of this V1AttributesBody.  # noqa: E501

        Attribute group  # noqa: E501

        :return: The group of this V1AttributesBody.  # noqa: E501
        :rtype: str
        """
        return self._group

    @group.setter
    def group(self, group):
        """Sets the group of this V1AttributesBody.

        Attribute group  # noqa: E501

        :param group: The group of this V1AttributesBody.  # noqa: E501
        :type: str
        """
        if group is None:
            raise ValueError("Invalid value for `group`, must not be `None`")  # noqa: E501

        self._group = group

    @property
    def group_labels(self):
        """Gets the group_labels of this V1AttributesBody.  # noqa: E501


        :return: The group_labels of this V1AttributesBody.  # noqa: E501
        :rtype: Apirestv1attributesGroupLabels
        """
        return self._group_labels

    @group_labels.setter
    def group_labels(self, group_labels):
        """Sets the group_labels of this V1AttributesBody.


        :param group_labels: The group_labels of this V1AttributesBody.  # noqa: E501
        :type: Apirestv1attributesGroupLabels
        """

        self._group_labels = group_labels

    @property
    def sort_order(self):
        """Gets the sort_order of this V1AttributesBody.  # noqa: E501

        Order of the attribute in its group  # noqa: E501

        :return: The sort_order of this V1AttributesBody.  # noqa: E501
        :rtype: int
        """
        return self._sort_order

    @sort_order.setter
    def sort_order(self, sort_order):
        """Sets the sort_order of this V1AttributesBody.

        Order of the attribute in its group  # noqa: E501

        :param sort_order: The sort_order of this V1AttributesBody.  # noqa: E501
        :type: int
        """

        self._sort_order = sort_order

    @property
    def localizable(self):
        """Gets the localizable of this V1AttributesBody.  # noqa: E501

        Whether the attribute is localizable, i.e. can have one value by locale  # noqa: E501

        :return: The localizable of this V1AttributesBody.  # noqa: E501
        :rtype: bool
        """
        return self._localizable

    @localizable.setter
    def localizable(self, localizable):
        """Sets the localizable of this V1AttributesBody.

        Whether the attribute is localizable, i.e. can have one value by locale  # noqa: E501

        :param localizable: The localizable of this V1AttributesBody.  # noqa: E501
        :type: bool
        """

        self._localizable = localizable

    @property
    def scopable(self):
        """Gets the scopable of this V1AttributesBody.  # noqa: E501

        Whether the attribute is scopable, i.e. can have one value by channel  # noqa: E501

        :return: The scopable of this V1AttributesBody.  # noqa: E501
        :rtype: bool
        """
        return self._scopable

    @scopable.setter
    def scopable(self, scopable):
        """Sets the scopable of this V1AttributesBody.

        Whether the attribute is scopable, i.e. can have one value by channel  # noqa: E501

        :param scopable: The scopable of this V1AttributesBody.  # noqa: E501
        :type: bool
        """

        self._scopable = scopable

    @property
    def available_locales(self):
        """Gets the available_locales of this V1AttributesBody.  # noqa: E501

        To make the attribute locale specfic, specify here for which locales it is specific  # noqa: E501

        :return: The available_locales of this V1AttributesBody.  # noqa: E501
        :rtype: list[str]
        """
        return self._available_locales

    @available_locales.setter
    def available_locales(self, available_locales):
        """Sets the available_locales of this V1AttributesBody.

        To make the attribute locale specfic, specify here for which locales it is specific  # noqa: E501

        :param available_locales: The available_locales of this V1AttributesBody.  # noqa: E501
        :type: list[str]
        """

        self._available_locales = available_locales

    @property
    def unique(self):
        """Gets the unique of this V1AttributesBody.  # noqa: E501

        Whether two values for the attribute cannot be the same  # noqa: E501

        :return: The unique of this V1AttributesBody.  # noqa: E501
        :rtype: bool
        """
        return self._unique

    @unique.setter
    def unique(self, unique):
        """Sets the unique of this V1AttributesBody.

        Whether two values for the attribute cannot be the same  # noqa: E501

        :param unique: The unique of this V1AttributesBody.  # noqa: E501
        :type: bool
        """

        self._unique = unique

    @property
    def useable_as_grid_filter(self):
        """Gets the useable_as_grid_filter of this V1AttributesBody.  # noqa: E501

        Whether the attribute can be used as a filter for the product grid in the PIM user interface  # noqa: E501

        :return: The useable_as_grid_filter of this V1AttributesBody.  # noqa: E501
        :rtype: bool
        """
        return self._useable_as_grid_filter

    @useable_as_grid_filter.setter
    def useable_as_grid_filter(self, useable_as_grid_filter):
        """Sets the useable_as_grid_filter of this V1AttributesBody.

        Whether the attribute can be used as a filter for the product grid in the PIM user interface  # noqa: E501

        :param useable_as_grid_filter: The useable_as_grid_filter of this V1AttributesBody.  # noqa: E501
        :type: bool
        """

        self._useable_as_grid_filter = useable_as_grid_filter

    @property
    def max_characters(self):
        """Gets the max_characters of this V1AttributesBody.  # noqa: E501

        Number maximum of characters allowed for the value of the attribute when the attribute type is `pim_catalog_text`, `pim_catalog_textarea` or `pim_catalog_identifier`  # noqa: E501

        :return: The max_characters of this V1AttributesBody.  # noqa: E501
        :rtype: int
        """
        return self._max_characters

    @max_characters.setter
    def max_characters(self, max_characters):
        """Sets the max_characters of this V1AttributesBody.

        Number maximum of characters allowed for the value of the attribute when the attribute type is `pim_catalog_text`, `pim_catalog_textarea` or `pim_catalog_identifier`  # noqa: E501

        :param max_characters: The max_characters of this V1AttributesBody.  # noqa: E501
        :type: int
        """

        self._max_characters = max_characters

    @property
    def validation_rule(self):
        """Gets the validation_rule of this V1AttributesBody.  # noqa: E501

        Validation rule type used to validate any attribute value when the attribute type is `pim_catalog_text` or `pim_catalog_identifier`  # noqa: E501

        :return: The validation_rule of this V1AttributesBody.  # noqa: E501
        :rtype: str
        """
        return self._validation_rule

    @validation_rule.setter
    def validation_rule(self, validation_rule):
        """Sets the validation_rule of this V1AttributesBody.

        Validation rule type used to validate any attribute value when the attribute type is `pim_catalog_text` or `pim_catalog_identifier`  # noqa: E501

        :param validation_rule: The validation_rule of this V1AttributesBody.  # noqa: E501
        :type: str
        """

        self._validation_rule = validation_rule

    @property
    def validation_regexp(self):
        """Gets the validation_regexp of this V1AttributesBody.  # noqa: E501

        Regexp expression used to validate any attribute value when the attribute type is `pim_catalog_text` or `pim_catalog_identifier`  # noqa: E501

        :return: The validation_regexp of this V1AttributesBody.  # noqa: E501
        :rtype: str
        """
        return self._validation_regexp

    @validation_regexp.setter
    def validation_regexp(self, validation_regexp):
        """Sets the validation_regexp of this V1AttributesBody.

        Regexp expression used to validate any attribute value when the attribute type is `pim_catalog_text` or `pim_catalog_identifier`  # noqa: E501

        :param validation_regexp: The validation_regexp of this V1AttributesBody.  # noqa: E501
        :type: str
        """

        self._validation_regexp = validation_regexp

    @property
    def wysiwyg_enabled(self):
        """Gets the wysiwyg_enabled of this V1AttributesBody.  # noqa: E501

        Whether the WYSIWYG interface is shown when the attribute type is `pim_catalog_textarea`  # noqa: E501

        :return: The wysiwyg_enabled of this V1AttributesBody.  # noqa: E501
        :rtype: bool
        """
        return self._wysiwyg_enabled

    @wysiwyg_enabled.setter
    def wysiwyg_enabled(self, wysiwyg_enabled):
        """Sets the wysiwyg_enabled of this V1AttributesBody.

        Whether the WYSIWYG interface is shown when the attribute type is `pim_catalog_textarea`  # noqa: E501

        :param wysiwyg_enabled: The wysiwyg_enabled of this V1AttributesBody.  # noqa: E501
        :type: bool
        """

        self._wysiwyg_enabled = wysiwyg_enabled

    @property
    def number_min(self):
        """Gets the number_min of this V1AttributesBody.  # noqa: E501

        Minimum integer value allowed when the attribute type is `pim_catalog_metric`, `pim_catalog_price` or `pim_catalog_number`  # noqa: E501

        :return: The number_min of this V1AttributesBody.  # noqa: E501
        :rtype: str
        """
        return self._number_min

    @number_min.setter
    def number_min(self, number_min):
        """Sets the number_min of this V1AttributesBody.

        Minimum integer value allowed when the attribute type is `pim_catalog_metric`, `pim_catalog_price` or `pim_catalog_number`  # noqa: E501

        :param number_min: The number_min of this V1AttributesBody.  # noqa: E501
        :type: str
        """

        self._number_min = number_min

    @property
    def number_max(self):
        """Gets the number_max of this V1AttributesBody.  # noqa: E501

        Maximum integer value allowed when the attribute type is `pim_catalog_metric`, `pim_catalog_price` or `pim_catalog_number`  # noqa: E501

        :return: The number_max of this V1AttributesBody.  # noqa: E501
        :rtype: str
        """
        return self._number_max

    @number_max.setter
    def number_max(self, number_max):
        """Sets the number_max of this V1AttributesBody.

        Maximum integer value allowed when the attribute type is `pim_catalog_metric`, `pim_catalog_price` or `pim_catalog_number`  # noqa: E501

        :param number_max: The number_max of this V1AttributesBody.  # noqa: E501
        :type: str
        """

        self._number_max = number_max

    @property
    def decimals_allowed(self):
        """Gets the decimals_allowed of this V1AttributesBody.  # noqa: E501

        Whether decimals are allowed when the attribute type is `pim_catalog_metric`, `pim_catalog_price` or `pim_catalog_number`  # noqa: E501

        :return: The decimals_allowed of this V1AttributesBody.  # noqa: E501
        :rtype: bool
        """
        return self._decimals_allowed

    @decimals_allowed.setter
    def decimals_allowed(self, decimals_allowed):
        """Sets the decimals_allowed of this V1AttributesBody.

        Whether decimals are allowed when the attribute type is `pim_catalog_metric`, `pim_catalog_price` or `pim_catalog_number`  # noqa: E501

        :param decimals_allowed: The decimals_allowed of this V1AttributesBody.  # noqa: E501
        :type: bool
        """

        self._decimals_allowed = decimals_allowed

    @property
    def negative_allowed(self):
        """Gets the negative_allowed of this V1AttributesBody.  # noqa: E501

        Whether negative values are allowed when the attribute type is `pim_catalog_metric` or `pim_catalog_number`  # noqa: E501

        :return: The negative_allowed of this V1AttributesBody.  # noqa: E501
        :rtype: bool
        """
        return self._negative_allowed

    @negative_allowed.setter
    def negative_allowed(self, negative_allowed):
        """Sets the negative_allowed of this V1AttributesBody.

        Whether negative values are allowed when the attribute type is `pim_catalog_metric` or `pim_catalog_number`  # noqa: E501

        :param negative_allowed: The negative_allowed of this V1AttributesBody.  # noqa: E501
        :type: bool
        """

        self._negative_allowed = negative_allowed

    @property
    def metric_family(self):
        """Gets the metric_family of this V1AttributesBody.  # noqa: E501

        Metric family when the attribute type is `pim_catalog_metric`  # noqa: E501

        :return: The metric_family of this V1AttributesBody.  # noqa: E501
        :rtype: str
        """
        return self._metric_family

    @metric_family.setter
    def metric_family(self, metric_family):
        """Sets the metric_family of this V1AttributesBody.

        Metric family when the attribute type is `pim_catalog_metric`  # noqa: E501

        :param metric_family: The metric_family of this V1AttributesBody.  # noqa: E501
        :type: str
        """

        self._metric_family = metric_family

    @property
    def default_metric_unit(self):
        """Gets the default_metric_unit of this V1AttributesBody.  # noqa: E501

        Default metric unit when the attribute type is `pim_catalog_metric`  # noqa: E501

        :return: The default_metric_unit of this V1AttributesBody.  # noqa: E501
        :rtype: str
        """
        return self._default_metric_unit

    @default_metric_unit.setter
    def default_metric_unit(self, default_metric_unit):
        """Sets the default_metric_unit of this V1AttributesBody.

        Default metric unit when the attribute type is `pim_catalog_metric`  # noqa: E501

        :param default_metric_unit: The default_metric_unit of this V1AttributesBody.  # noqa: E501
        :type: str
        """

        self._default_metric_unit = default_metric_unit

    @property
    def date_min(self):
        """Gets the date_min of this V1AttributesBody.  # noqa: E501

        Minimum date allowed when the attribute type is `pim_catalog_date`  # noqa: E501

        :return: The date_min of this V1AttributesBody.  # noqa: E501
        :rtype: datetime
        """
        return self._date_min

    @date_min.setter
    def date_min(self, date_min):
        """Sets the date_min of this V1AttributesBody.

        Minimum date allowed when the attribute type is `pim_catalog_date`  # noqa: E501

        :param date_min: The date_min of this V1AttributesBody.  # noqa: E501
        :type: datetime
        """

        self._date_min = date_min

    @property
    def date_max(self):
        """Gets the date_max of this V1AttributesBody.  # noqa: E501

        Maximum date allowed when the attribute type is `pim_catalog_date`  # noqa: E501

        :return: The date_max of this V1AttributesBody.  # noqa: E501
        :rtype: datetime
        """
        return self._date_max

    @date_max.setter
    def date_max(self, date_max):
        """Sets the date_max of this V1AttributesBody.

        Maximum date allowed when the attribute type is `pim_catalog_date`  # noqa: E501

        :param date_max: The date_max of this V1AttributesBody.  # noqa: E501
        :type: datetime
        """

        self._date_max = date_max

    @property
    def allowed_extensions(self):
        """Gets the allowed_extensions of this V1AttributesBody.  # noqa: E501

        Extensions allowed when the attribute type is `pim_catalog_file` or `pim_catalog_image`  # noqa: E501

        :return: The allowed_extensions of this V1AttributesBody.  # noqa: E501
        :rtype: list[str]
        """
        return self._allowed_extensions

    @allowed_extensions.setter
    def allowed_extensions(self, allowed_extensions):
        """Sets the allowed_extensions of this V1AttributesBody.

        Extensions allowed when the attribute type is `pim_catalog_file` or `pim_catalog_image`  # noqa: E501

        :param allowed_extensions: The allowed_extensions of this V1AttributesBody.  # noqa: E501
        :type: list[str]
        """

        self._allowed_extensions = allowed_extensions

    @property
    def max_file_size(self):
        """Gets the max_file_size of this V1AttributesBody.  # noqa: E501

        Max file size in MB when the attribute type is `pim_catalog_file` or `pim_catalog_image`  # noqa: E501

        :return: The max_file_size of this V1AttributesBody.  # noqa: E501
        :rtype: str
        """
        return self._max_file_size

    @max_file_size.setter
    def max_file_size(self, max_file_size):
        """Sets the max_file_size of this V1AttributesBody.

        Max file size in MB when the attribute type is `pim_catalog_file` or `pim_catalog_image`  # noqa: E501

        :param max_file_size: The max_file_size of this V1AttributesBody.  # noqa: E501
        :type: str
        """

        self._max_file_size = max_file_size

    @property
    def reference_data_name(self):
        """Gets the reference_data_name of this V1AttributesBody.  # noqa: E501

        Reference entity code when the attribute type is `akeneo_reference_entity` or `akeneo_reference_entity_collection` OR Asset family code when the attribute type is `pim_catalog_asset_collection`  # noqa: E501

        :return: The reference_data_name of this V1AttributesBody.  # noqa: E501
        :rtype: str
        """
        return self._reference_data_name

    @reference_data_name.setter
    def reference_data_name(self, reference_data_name):
        """Sets the reference_data_name of this V1AttributesBody.

        Reference entity code when the attribute type is `akeneo_reference_entity` or `akeneo_reference_entity_collection` OR Asset family code when the attribute type is `pim_catalog_asset_collection`  # noqa: E501

        :param reference_data_name: The reference_data_name of this V1AttributesBody.  # noqa: E501
        :type: str
        """

        self._reference_data_name = reference_data_name

    @property
    def default_value(self):
        """Gets the default_value of this V1AttributesBody.  # noqa: E501

        Default value for a Yes/No attribute, applied when creating a new product or product model (only available since the 5.0)  # noqa: E501

        :return: The default_value of this V1AttributesBody.  # noqa: E501
        :rtype: bool
        """
        return self._default_value

    @default_value.setter
    def default_value(self, default_value):
        """Sets the default_value of this V1AttributesBody.

        Default value for a Yes/No attribute, applied when creating a new product or product model (only available since the 5.0)  # noqa: E501

        :param default_value: The default_value of this V1AttributesBody.  # noqa: E501
        :type: bool
        """

        self._default_value = default_value

    @property
    def table_configuration(self):
        """Gets the table_configuration of this V1AttributesBody.  # noqa: E501

        Configuration of the Table attribute (columns)  # noqa: E501

        :return: The table_configuration of this V1AttributesBody.  # noqa: E501
        :rtype: list[Apirestv1attributesTableConfiguration]
        """
        return self._table_configuration

    @table_configuration.setter
    def table_configuration(self, table_configuration):
        """Sets the table_configuration of this V1AttributesBody.

        Configuration of the Table attribute (columns)  # noqa: E501

        :param table_configuration: The table_configuration of this V1AttributesBody.  # noqa: E501
        :type: list[Apirestv1attributesTableConfiguration]
        """

        self._table_configuration = table_configuration

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1AttributesBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1AttributesBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
